In [ ]:
import pandas as pd
import datetime as dt

df = pd.read_csv("./Trading Data/GBPJPY_H1_201801020000_202609160000.csv",sep='\t')
dateTime = []
df = df.reset_index()  # Make sure indexes pair with number of rows

for index, row in df.iterrows():
    # print(row['Date'])
    date_array = row['Date'].split('.')
    time_array = row['Time'].split(':')
    new_datetime = dt.datetime(int(date_array[0]), int(date_array[1]), int(date_array[2]), int(time_array[0]), int(time_array[1]), int(time_array[2]), 0)
    # print(new_datetime)
    dateTime.append(new_datetime)

df = df.drop('Date', axis=1)
df = df.drop('Time', axis=1)
df = df.drop('index', axis=1)

df['Date'] = dateTime

df.to_csv("./Trading Data/GBPJPY_H1_201801020000_202609160000_MODIFY.csv", sep='\t')

          Open     High      Low    Close  Tickvol  Volume  Spread
0      152.107  152.213  151.939  152.140     2417       0      57
1      152.157  152.435  152.101  152.356    16368       0       3
2      152.356  152.438  152.298  152.337     3428       0       4
3      152.337  152.397  152.291  152.329     3844       0       2
4      152.329  152.378  152.279  152.305     3067       0       2
...        ...      ...      ...      ...      ...     ...     ...
54157  209.053  209.134  208.995  209.074     4698       0       1
54158  209.075  209.113  209.051  209.069     4569       0       0
54159  209.070  209.083  208.973  209.018     4011       0       0
54160  209.013  209.028  208.980  209.021     2354       0       0
54161  208.875  208.979  208.817  208.830      968       0     161

[54162 rows x 7 columns]

In [32]:
import pandas as pd
import datetime as dt
from ta.volatility import AverageTrueRange

timezone = "Europe/London"

df = pd.read_csv("./Trading Data/GBPJPY_H1.csv",sep=',', parse_dates=['Date'], index_col='Date')
df.index = pd.to_datetime(df.index, utc=True).tz_convert(timezone)

indicator_atr = AverageTrueRange(df['High'], df['Low'], df['Close'], window=14)
df['ATR'] = indicator_atr._atr

df

,Open,High,Low,Close,Tickvol,ATR
Date,,,,,,
2010-09-03 12:00:00+01:00,130.110,130.180,129.995,129.995,8927,0.000000
2010-09-03 13:00:00+01:00,130.000,131.670,129.955,131.265,11185,0.000000
2010-09-03 14:00:00+01:00,131.270,131.435,130.890,130.925,13216,0.000000
2010-09-03 15:00:00+01:00,130.915,130.915,130.070,130.210,13223,0.000000
2010-09-03 16:00:00+01:00,130.210,130.580,130.190,130.480,11902,0.000000
...,...,...,...,...,...,...
2026-09-17 05:00:00+01:00,208.787,208.823,208.746,208.774,5768,0.224504
2026-09-17 06:00:00+01:00,208.776,208.776,208.290,208.356,10475,0.243182
2026-09-17 07:00:00+01:00,208.356,208.550,208.226,208.537,21429,0.248955
2026-09-17 08:00:00+01:00,208.536,208.604,208.333,208.432,15583,0.250530
2026-09-17 09:00:00+01:00,208.433,208.668,208.391,208.647,10831,0.252421

In [10]:
import pandas as pd
from ta.volatility import AverageTrueRange
from pytz import timezone
from backtesting import Backtest, Strategy

# class Util:
#     def convertICMarketTimezoneToLondonTimeszone(year, month, day, timeArray):
#         icMarketTz = timezone('Asia/Istanbul')
#         londonTz = timezone('Europe/London')

#         icMarketDt = dt.datetime(year, month, day, int(timeArray[0]), int(timeArray[1]), int(timeArray[2]), 0, icMarketTz)
#         londonDt = icMarketDt.astimezone(londonTz)
#         print(icMarketDt)
#         print(londonDt)
        

#         return londonDt

class OpeningRangeBreakout(Strategy):

    def init(self):
        self.opening_range_high = None
        self.opening_range_low = None
        self.index = 0

    def next(self):
        print(self.data)

    

df = pd.read_csv("./Trading Data/GBPJPY_H1.csv",sep=',', parse_dates=['Date'], index_col='Date')
df = df.loc['2026-09-15' : '2026-09-17']

indicator_atr = AverageTrueRange(df['High'], df['Low'], df['Close'], window=14)
df['ATR'] = indicator_atr._atr

bt = Backtest(df, OpeningRangeBreakout)

bt.run()

<Data i=1 (2026-09-15 01:00:00) Open=208.723, High=208.748, Low=208.63, Close=208.692, Tickvol=7833.0, ATR=0.0, Volume=nan>
<Data i=2 (2026-09-15 02:00:00) Open=208.69, High=208.855, Low=208.667, Close=208.786, Tickvol=8519.0, ATR=0.0, Volume=nan>
<Data i=3 (2026-09-15 03:00:00) Open=208.781, High=208.788, Low=208.544, Close=208.551, Tickvol=11125.0, ATR=0.0, Volume=nan>
<Data i=4 (2026-09-15 04:00:00) Open=208.55, High=208.649, Low=208.517, Close=208.636, Tickvol=10485.0, ATR=0.0, Volume=nan>
<Data i=5 (2026-09-15 05:00:00) Open=208.636, High=208.868, Low=208.556, Close=208.718, Tickvol=12192.0, ATR=0.0, Volume=nan>
<Data i=6 (2026-09-15 06:00:00) Open=208.719, High=208.724, Low=208.486, Close=208.65, Tickvol=12323.0, ATR=0.0, Volume=nan>
<Data i=7 (2026-09-15 07:00:00) Open=208.652, High=208.812, Low=208.514, Close=208.771, Tickvol=14008.0, ATR=0.0, Volume=nan>
<Data i=8 (2026-09-15 08:00:00) Open=208.773, High=209.09, Low=208.625, Close=208.842, Tickvol=17362.0, ATR=0.0, Volume=nan>
<Data i=9 (2026-09-15 09:00:00) Open=208.842, High=208.873, Low=208.724, Close=208.79, Tickvol=13722.0, ATR=0.0, Volume=nan>
<Data i=10 (2026-09-15 10:00:00) Open=208.788, High=208.789, Low=208.558, Close=208.655, Tickvol=11315.0, ATR=0.0, Volume=nan>
<Data i=11 (2026-09-15 11:00:00) Open=208.655, High=208.859, Low=208.607, Close=208.849, Tickvol=13629.0, ATR=0.0, Volume=nan>
<Data i=12 (2026-09-15 12:00:00) Open=208.847, High=209.057, Low=208.829, Close=208.925, Tickvol=20199.0, ATR=0.0, Volume=nan>
<Data i=13 (2026-09-15 13:00:00) Open=208.928, High=209.179, Low=208.87, Close=209.117, Tickvol=20503.0, ATR=0.2464999999999975, Volume=nan>
<Data i=14 (2026-09-15 14:00:00) Open=209.116, High=209.211, Low=208.99, Close=209.168, Tickvol=20149.0, ATR=0.24467857142856936, Volume=nan>
<Data i=15 (2026-09-15 15:00:00) Open=209.167, High=209.224, Low=208.885, Close=209.04, Tickvol=15461.0, ATR=0.2514158163265286, Volume=nan>
<Data i=16 (2026-09-15 16:00:00) Open=209.04, High=209.072, Low=208.907, Close=209.047, Tickvol=9114.0, ATR=0.24524325801749028, Volume=nan>
<Data i=17 (2026-09-15 17:00:00) Open=209.047, High=209.127, Low=208.993, Close=209.073, Tickvol=7140.0, ATR=0.23729731101624202, Volume=nan>
<Data i=18 (2026-09-15 18:00:00) Open=209.071, High=209.106, Low=209.047, Close=209.066, Tickvol=6695.0, ATR=0.224561788800796, Volume=nan>
<Data i=19 (2026-09-15 19:00:00) Open=209.064, High=209.082, Low=208.969, Close=209.015, Tickvol=6146.0, ATR=0.2165930896007391, Volume=nan>
<Data i=20 (2026-09-15 20:00:00) Open=209.011, High=209.036, Low=208.98, Close=209.021, Tickvol=5189.0, ATR=0.20512215462925856, Volume=nan>
<Data i=21 (2026-09-15 21:00:00) Open=208.88, High=209.006, Low=208.872, Close=208.889, Tickvol=1780.0, ATR=0.20111342929859527, Volume=nan>
<Data i=22 (2026-09-15 22:00:00) Open=208.895, High=209.029, Low=208.895, Close=209.019, Tickvol=5661.0, ATR=0.19674818434869465, Volume=nan>
<Data i=23 (2026-09-15 23:00:00) Open=209.018, High=209.342, Low=209.007, Close=209.169, Tickvol=10848.0, ATR=0.20662331403807419, Volume=nan>
<Data i=24 (2026-09-16 00:00:00) Open=209.168, High=209.309, Low=208.982, Close=209.259, Tickvol=24893.0, ATR=0.21522164874964017, Volume=nan>
<Data i=25 (2026-09-16 01:00:00) Open=209.26, High=209.394, Low=209.168, Close=209.29, Tickvol=8935.0, ATR=0.21599153098180865, Volume=nan>
<Data i=26 (2026-09-16 02:00:00) Open=209.286, High=209.329, Low=209.205, Close=209.259, Tickvol=8177.0, ATR=0.20942070734025053, Volume=nan>
<Data i=27 (2026-09-16 03:00:00) Open=209.258, High=209.467, Low=209.24, Close=209.431, Tickvol=7843.0, ATR=0.21067637110166149, Volume=nan>
<Data i=28 (2026-09-16 04:00:00) Open=209.433, High=209.457, Low=209.381, Close=209.414, Tickvol=4702.0, ATR=0.2010566303086852, Volume=nan>
<Data i=29 (2026-09-16 05:00:00) Open=209.413, High=209.459, Low=209.342, Close=209.361, Tickvol=6679.0, ATR=0.19505258528663558, Volume=nan>
<Data i=30 (2026-09-16 06:00:00) Open=209.354, High=209.407, Low=208.893, Close=208.903, Tickvol=12104.0, ATR=0.21783454348044803, Volume=nan>
<Data i=31 (2026-09-16 07:00:00) Open=208.901, High=209.012, Low=208.715, Close=208.775, Tickvol=12512.0, ATR=0.2234892189461301, Volume=nan>
<Data i=32 (2026-09-16 08:00:00) Open=208.78, High=208.947, Low=208.711, Close=208.937, Tickvol=10916.0, ATR=0.22438284616426296, Volume=nan>
<Data i=33 (2026-09-16 09:00:00) Open=208.933, High=208.976, Low=208.834, Close=208.919, Tickvol=7807.0, ATR=0.2184983571525296, Volume=nan>
<Data i=34 (2026-09-16 10:00:00) Open=208.921, High=209.002, Low=208.887, Close=208.94, Tickvol=5742.0, ATR=0.21110561735592098, Volume=nan>
<Data i=35 (2026-09-16 11:00:00) Open=208.94, High=208.971, Low=208.563, Close=208.612, Tickvol=13560.0, ATR=0.22516950183049916, Volume=nan>
<Data i=36 (2026-09-16 12:00:00) Open=208.617, High=208.911, Low=208.597, Close=208.881, Tickvol=11160.0, ATR=0.23151453741403444, Volume=nan>
<Data i=37 (2026-09-16 13:00:00) Open=208.885, High=208.987, Low=208.834, Close=208.846, Tickvol=14810.0, ATR=0.22590635617017424, Volume=nan>
<Data i=38 (2026-09-16 14:00:00) Open=208.844, High=208.876, Low=208.634, Close=208.641, Tickvol=14785.0, ATR=0.22705590215802027, Volume=nan>
<Data i=39 (2026-09-16 15:00:00) Open=208.642, High=208.653, Low=208.464, Close=208.512, Tickvol=18391.0, ATR=0.22433762343244687, Volume=nan>
<Data i=40 (2026-09-16 16:00:00) Open=208.51, High=208.745, Low=208.509, Close=208.546, Tickvol=8750.0, ATR=0.22517065033013053, Volume=nan>
<Data i=41 (2026-09-16 17:00:00) Open=208.548, High=208.58, Low=208.447, Close=208.447, Tickvol=7727.0, ATR=0.21858703244940764, Volume=nan>
<Data i=42 (2026-09-16 18:00:00) Open=208.474, High=208.745, Low=208.339, Close=208.639, Tickvol=35650.0, ATR=0.23197367298873608, Volume=nan>
<Data i=43 (2026-09-16 19:00:00) Open=208.64, High=209.055, Low=208.579, Close=209.055, Tickvol=28303.0, ATR=0.249404124918112, Volume=nan>
<Data i=44 (2026-09-16 20:00:00) Open=209.054, High=209.248, Low=209.003, Close=209.033, Tickvol=7839.0, ATR=0.24908954456681862, Volume=nan>
<Data i=45 (2026-09-16 21:00:00) Open=208.863, High=209.071, Low=208.863, Close=208.975, Tickvol=1106.0, ATR=0.24615457709776004, Volume=nan>
<Data i=46 (2026-09-16 22:00:00) Open=208.975, High=209.096, Low=208.974, Close=209.061, Tickvol=4885.0, ATR=0.23728639301934962, Volume=nan>
<Data i=47 (2026-09-16 23:00:00) Open=209.062, High=209.09, Low=208.788, Close=208.807, Tickvol=9886.0, ATR=0.24190879351796696, Volume=nan>
<Data i=48 (2026-09-17 00:00:00) Open=208.807, High=208.897, Low=208.654, Close=208.884, Tickvol=18185.0, ATR=0.24198673683811184, Volume=nan>
<Data i=49 (2026-09-17 01:00:00) Open=208.882, High=208.958, Low=208.691, Close=208.807, Tickvol=12713.0, ATR=0.24377339849253213, Volume=nan>
<Data i=50 (2026-09-17 02:00:00) Open=208.806, High=208.974, Low=208.777, Close=208.832, Tickvol=7515.0, ATR=0.24043244145735146, Volume=nan>
<Data i=51 (2026-09-17 03:00:00) Open=208.834, High=208.846, Low=208.676, Close=208.787, Tickvol=8733.0, ATR=0.23540155278182748, Volume=nan>
<Data i=52 (2026-09-17 04:00:00) Open=208.787, High=208.823, Low=208.746, Close=208.774, Tickvol=5768.0, ATR=0.22408715615455393, Volume=nan>
<Data i=53 (2026-09-17 05:00:00) Open=208.776, High=208.776, Low=208.29, Close=208.356, Tickvol=10475.0, ATR=0.24279521642922997, Volume=nan>
<Data i=54 (2026-09-17 06:00:00) Open=208.356, High=208.55, Low=208.226, Close=208.537, Tickvol=21429.0, ATR=0.2485955581128573, Volume=nan>
<Data i=55 (2026-09-17 07:00:00) Open=208.536, High=208.604, Low=208.333, Close=208.432, Tickvol=15583.0, ATR=0.2501958753905114, Volume=nan>
<Data i=56 (2026-09-17 08:00:00) Open=208.433, High=208.668, Low=208.391, Close=208.647, Tickvol=10831.0, ATR=0.2521104557197617, Volume=nan>

Start                     2026-09-15 00:00:00
End                       2026-09-17 08:00:00
Duration                      2 days 08:00:00
Exposure Time [%]                         0.0
Equity Final [$]                      10000.0
Equity Peak [$]                       10000.0
Return [%]                                0.0
Buy & Hold Return [%]                -0.03641
Return (Ann.) [%]                         0.0
Volatility (Ann.) [%]                     0.0
CAGR [%]                                  0.0
Sharpe Ratio                               --
Sortino Ratio                              --
Calmar Ratio                               --
Alpha [%]                                 0.0
Beta                                      0.0
Max. Drawdown [%]                        -0.0
Avg. Drawdown [%]                          --
Max. Drawdown Duration                     --
Avg. Drawdown Duration                     --
# Trades                                    0
Win Rate [%]                               --
Best Trade [%]                             --
Worst Trade [%]                            --
Avg. Trade [%]                             --
Max. Trade Duration                        --
Avg. Trade Duration                        --
Profit Factor                              --
Expectancy [%]                             --
SQN                                        --
Kelly Criterion                            --
_strategy                 OpeningRangeBrea...
_equity_curve                             ...
_trades                   Empty DataFrame
...
dtype: object

In [11]:
import pandas as pd
import datetime as di
from ta.volatility import AverageTrueRange
from backtesting import Backtest, Strategy

class OpeningRangeBreakout(Strategy):
    # variables
    range_to_consider = 5

    # fixed variables
    close_range_hour = 10
    open_range_hour = close_range_hour - range_to_consider

    def init(self):
        self.current_day = None
        self.opening_range_high = None
        self.opening_range_low = None

    def reset_range(self, day):
        self.current_day = day
        self.opening_range_high = None
        self.opening_range_low = None

    def next(self):
        t = self.data.index[-1]
        current_bar_date = self.data.index[-1].date()

        print(self.data)
        # print(current_bar_date)

        if (self.current_day != current_bar_date):
            self.reset_range(current_bar_date)
            print(f"new date {current_bar_date}")

        if self.open_range_hour < t.time().hour and t.time().hour <= self.close_range_hour:
            if self.opening_range_high is not None:
                self.opening_range_high = max(self.opening_range_high, self.data.High[-1])
            else:
                self.opening_range_high = self.data.High[-1]

            if self.opening_range_low is not None:
                    self.opening_range_low = min(self.opening_range_low, self.data.Low[-1])
            else:
                self.opening_range_low = self.data.Low[-1]

            if t.time().hour < self.close_range_hour:
                return

        if t.time().hour == self.close_range_hour:
            print(f"opening rang high is {self.opening_range_high}")
            print(f"opening rang low is {self.opening_range_low}")

df = pd.read_csv("./Trading Data/GBPJPY_H1.csv",sep=',', parse_dates=['Date'], index_col='Date')
df = df.loc['2026-09-10' : '2026-09-16']

indicator_atr = AverageTrueRange(df['High'], df['Low'], df['Close'], window=14)
df['ATR'] = indicator_atr._atr

bt = Backtest(df, OpeningRangeBreakout, cash=25000)

bt.run()

bt.plot()

<Data i=1 (2026-09-10 01:00:00) Open=208.197, High=208.282, Low=208.003, Close=208.008, Tickvol=26032.0, ATR=0.0, Volume=nan>
new date 2026-09-10
<Data i=2 (2026-09-10 02:00:00) Open=208.008, High=208.151, Low=207.846, Close=208.02, Tickvol=16264.0, ATR=0.0, Volume=nan>
<Data i=3 (2026-09-10 03:00:00) Open=208.021, High=208.05, Low=207.89, Close=207.931, Tickvol=11071.0, ATR=0.0, Volume=nan>
<Data i=4 (2026-09-10 04:00:00) Open=207.932, High=208.006, Low=207.822, Close=208.001, Tickvol=6528.0, ATR=0.0, Volume=nan>
<Data i=5 (2026-09-10 05:00:00) Open=208.003, High=208.27, Low=207.946, Close=208.249, Tickvol=9139.0, ATR=0.0, Volume=nan>
<Data i=6 (2026-09-10 06:00:00) Open=208.25, High=208.273, Low=207.98, Close=207.993, Tickvol=12326.0, ATR=0.0, Volume=nan>
<Data i=7 (2026-09-10 07:00:00) Open=207.997, High=208.115, Low=207.833, Close=207.9, Tickvol=19218.0, ATR=0.0, Volume=nan>
<Data i=8 (2026-09-10 08:00:00) Open=207.913, High=208.276, Low=207.903, Close=208.262, Tickvol=14642.0, ATR=0.0, Volume=nan>
<Data i=9 (2026-09-10 09:00:00) Open=208.266, High=208.328, Low=208.124, Close=208.25, Tickvol=14030.0, ATR=0.0, Volume=nan>
<Data i=10 (2026-09-10 10:00:00) Open=208.25, High=208.709, Low=208.227, Close=208.604, Tickvol=14288.0, ATR=0.0, Volume=nan>
opening rang high is 208.709
opening rang low is 207.833
<Data i=11 (2026-09-10 11:00:00) Open=208.604, High=208.646, Low=208.484, Close=208.55, Tickvol=18803.0, ATR=0.0, Volume=nan>
<Data i=12 (2026-09-10 12:00:00) Open=208.548, High=208.884, Low=208.352, Close=208.539, Tickvol=29364.0, ATR=0.0, Volume=nan>
<Data i=13 (2026-09-10 13:00:00) Open=208.539, High=208.553, Low=208.147, Close=208.195, Tickvol=25432.0, ATR=0.3052142857142895, Volume=nan>
<Data i=14 (2026-09-10 14:00:00) Open=208.191, High=208.377, Low=207.939, Close=208.215, Tickvol=22424.0, ATR=0.31469897959184145, Volume=nan>
<Data i=15 (2026-09-10 15:00:00) Open=208.215, High=208.51, Low=208.159, Close=208.457, Tickvol=20890.0, ATR=0.31729190962099557, Volume=nan>
<Data i=16 (2026-09-10 16:00:00) Open=208.458, High=208.782, Low=208.452, Close=208.63, Tickvol=12729.0, ATR=0.3181996303623539, Volume=nan>
<Data i=17 (2026-09-10 17:00:00) Open=208.631, High=208.751, Low=208.56, Close=208.565, Tickvol=9048.0, ATR=0.3091139424793288, Volume=nan>
<Data i=18 (2026-09-10 18:00:00) Open=208.564, High=208.638, Low=208.522, Close=208.531, Tickvol=9841.0, ATR=0.29532008944509197, Volume=nan>
<Data i=19 (2026-09-10 19:00:00) Open=208.533, High=208.562, Low=208.471, Close=208.499, Tickvol=9471.0, ATR=0.2807257973418717, Volume=nan>
<Data i=20 (2026-09-10 20:00:00) Open=208.5, High=208.736, Low=208.486, Close=208.63, Tickvol=7742.0, ATR=0.278531097531738, Volume=nan>
<Data i=21 (2026-09-10 21:00:00) Open=208.453, High=208.564, Low=208.356, Close=208.466, Tickvol=1797.0, ATR=0.27820744770804245, Volume=nan>
<Data i=22 (2026-09-10 22:00:00) Open=208.585, High=208.772, Low=208.582, Close=208.585, Tickvol=5174.0, ATR=0.28019263001460964, Volume=nan>
<Data i=23 (2026-09-10 23:00:00) Open=208.585, High=208.862, Low=208.576, Close=208.68, Tickvol=11871.0, ATR=0.28060744215642336, Volume=nan>
<Data i=24 (2026-09-11 00:00:00) Open=208.68, High=208.911, Low=208.547, Close=208.814, Tickvol=26203.0, ATR=0.28656405343096486, Volume=nan>
new date 2026-09-11
<Data i=25 (2026-09-11 01:00:00) Open=208.814, High=208.836, Low=208.395, Close=208.5, Tickvol=20112.0, ATR=0.2975951924716104, Volume=nan>
<Data i=26 (2026-09-11 02:00:00) Open=208.497, High=208.654, Low=208.456, Close=208.473, Tickvol=17077.0, ATR=0.2904812501522102, Volume=nan>
<Data i=27 (2026-09-11 03:00:00) Open=208.471, High=208.524, Low=208.372, Close=208.429, Tickvol=14929.0, ATR=0.28058973228419426, Volume=nan>
<Data i=28 (2026-09-11 04:00:00) Open=208.429, High=208.501, Low=208.317, Close=208.404, Tickvol=11690.0, ATR=0.2736904656924659, Volume=nan>
<Data i=29 (2026-09-11 05:00:00) Open=208.405, High=208.413, Low=208.085, Close=208.133, Tickvol=13129.0, ATR=0.2775697181430043, Volume=nan>
<Data i=30 (2026-09-11 06:00:00) Open=208.125, High=208.563, Low=208.125, Close=208.512, Tickvol=14794.0, ATR=0.2890290239899317, Volume=nan>
<Data i=31 (2026-09-11 07:00:00) Open=208.513, High=208.541, Low=208.348, Close=208.44, Tickvol=17423.0, ATR=0.28216980799064967, Volume=nan>
<Data i=32 (2026-09-11 08:00:00) Open=208.439, High=208.561, Low=208.099, Close=208.125, Tickvol=14650.0, ATR=0.2950148217056045, Volume=nan>
<Data i=33 (2026-09-11 09:00:00) Open=208.121, High=208.305, Low=208.034, Close=208.169, Tickvol=13969.0, ATR=0.2932994772980623, Volume=nan>
<Data i=34 (2026-09-11 10:00:00) Open=208.167, High=208.227, Low=207.908, Close=207.934, Tickvol=12645.0, ATR=0.2951352289196305, Volume=nan>
opening rang high is 208.563
opening rang low is 207.908
<Data i=35 (2026-09-11 11:00:00) Open=207.936, High=208.132, Low=207.823, Close=207.988, Tickvol=20842.0, ATR=0.2961255697110853, Volume=nan>
<Data i=36 (2026-09-11 12:00:00) Open=207.985, High=208.331, Low=207.435, Close=207.534, Tickvol=34024.0, ATR=0.3389737433031496, Volume=nan>
<Data i=37 (2026-09-11 13:00:00) Open=207.533, High=207.7, Low=207.3, Close=207.603, Tickvol=33171.0, ATR=0.3433327616386373, Volume=nan>
<Data i=38 (2026-09-11 14:00:00) Open=207.598, High=207.802, Low=207.563, Close=207.641, Tickvol=26573.0, ATR=0.3358804215215921, Volume=nan>
<Data i=39 (2026-09-11 15:00:00) Open=207.645, High=207.828, Low=207.559, Close=207.816, Tickvol=25361.0, ATR=0.3311032485557645, Volume=nan>
<Data i=40 (2026-09-11 16:00:00) Open=207.816, High=207.873, Low=207.757, Close=207.862, Tickvol=21506.0, ATR=0.31573873080178033, Volume=nan>
<Data i=41 (2026-09-11 17:00:00) Open=207.861, High=207.902, Low=207.759, Close=207.854, Tickvol=17096.0, ATR=0.3034002500302247, Volume=nan>
<Data i=42 (2026-09-11 18:00:00) Open=207.852, High=207.924, Low=207.817, Close=207.901, Tickvol=10991.0, ATR=0.28937166074235143, Volume=nan>
<Data i=43 (2026-09-11 19:00:00) Open=207.901, High=207.964, Low=207.87, Close=207.884, Tickvol=12901.0, ATR=0.27541654211789734, Volume=nan>
<Data i=44 (2026-09-11 20:00:00) Open=207.885, High=207.952, Low=207.591, Close=207.716, Tickvol=9074.0, ATR=0.2815296462523325, Volume=nan>
<Data i=45 (2026-09-13 21:00:00) Open=207.28, High=207.559, Low=207.271, Close=207.506, Tickvol=7134.0, ATR=0.29320610009145315, Volume=nan>
new date 2026-09-13
<Data i=46 (2026-09-13 22:00:00) Open=207.514, High=207.912, Low=207.425, Close=207.818, Tickvol=13176.0, ATR=0.3070485215134918, Volume=nan>
<Data i=47 (2026-09-13 23:00:00) Open=207.819, High=207.85, Low=207.482, Close=207.5, Tickvol=16793.0, ATR=0.311402198548242, Volume=nan>
<Data i=48 (2026-09-14 00:00:00) Open=207.503, High=207.822, Low=207.455, Close=207.706, Tickvol=29155.0, ATR=0.31537347008050975, Volume=nan>
new date 2026-09-14
<Data i=49 (2026-09-14 01:00:00) Open=207.704, High=207.937, Low=207.658, Close=207.795, Tickvol=20393.0, ATR=0.31277536507476084, Volume=nan>
<Data i=50 (2026-09-14 02:00:00) Open=207.796, High=208.182, Low=207.796, Close=208.128, Tickvol=10864.0, ATR=0.31807712471227795, Volume=nan>
<Data i=51 (2026-09-14 03:00:00) Open=208.128, High=208.191, Low=208.018, Close=208.053, Tickvol=11685.0, ATR=0.3077144729471154, Volume=nan>
<Data i=52 (2026-09-14 04:00:00) Open=208.052, High=208.07, Low=207.893, Close=207.978, Tickvol=16119.0, ATR=0.2983777248794638, Volume=nan>
<Data i=53 (2026-09-14 05:00:00) Open=207.978, High=208.097, Low=207.892, Close=208.015, Tickvol=18324.0, ATR=0.2917078873880744, Volume=nan>
<Data i=54 (2026-09-14 06:00:00) Open=208.013, High=208.302, Low=207.876, Close=208.13, Tickvol=25465.0, ATR=0.3013001811460682, Volume=nan>
<Data i=55 (2026-09-14 07:00:00) Open=208.132, High=208.362, Low=208.07, Close=208.306, Tickvol=17753.0, ATR=0.30063588249277773, Volume=nan>
<Data i=56 (2026-09-14 08:00:00) Open=208.307, High=208.448, Low=208.208, Close=208.39, Tickvol=16391.0, ATR=0.2963047480290085, Volume=nan>
<Data i=57 (2026-09-14 09:00:00) Open=208.39, High=208.476, Low=208.191, Close=208.449, Tickvol=14916.0, ATR=0.2954972660269362, Volume=nan>
<Data i=58 (2026-09-14 10:00:00) Open=208.447, High=208.625, Low=208.4, Close=208.45, Tickvol=10982.0, ATR=0.29046174702501176, Volume=nan>
opening rang high is 208.625
opening rang low is 207.876
<Data i=59 (2026-09-14 11:00:00) Open=208.45, High=208.589, Low=208.383, Close=208.533, Tickvol=9808.0, ATR=0.284428765094653, Volume=nan>
<Data i=60 (2026-09-14 12:00:00) Open=208.536, High=208.682, Low=208.477, Close=208.578, Tickvol=25555.0, ATR=0.2787552818736052, Volume=nan>
<Data i=61 (2026-09-14 13:00:00) Open=208.578, High=208.767, Low=208.515, Close=208.631, Tickvol=27496.0, ATR=0.2768441903112055, Volume=nan>
<Data i=62 (2026-09-14 14:00:00) Open=208.632, High=208.695, Low=208.391, Close=208.482, Tickvol=31883.0, ATR=0.2787838910032624, Volume=nan>
<Data i=63 (2026-09-14 15:00:00) Open=208.481, High=208.533, Low=208.187, Close=208.354, Tickvol=30842.0, ATR=0.2835850416458848, Volume=nan>
<Data i=64 (2026-09-14 16:00:00) Open=208.354, High=208.505, Low=208.203, Close=208.409, Tickvol=19429.0, ATR=0.2849003958140353, Volume=nan>
<Data i=65 (2026-09-14 17:00:00) Open=208.408, High=208.569, Low=208.39, Close=208.56, Tickvol=9499.0, ATR=0.27733608182731867, Volume=nan>
<Data i=66 (2026-09-14 18:00:00) Open=208.56, High=208.585, Low=208.056, Close=208.114, Tickvol=10918.0, ATR=0.29531207598250997, Volume=nan>
<Data i=67 (2026-09-14 19:00:00) Open=208.114, High=208.389, Low=208.114, Close=208.376, Tickvol=10659.0, ATR=0.29386121341233107, Volume=nan>
<Data i=68 (2026-09-14 20:00:00) Open=208.376, High=208.429, Low=208.332, Close=208.332, Tickvol=6105.0, ATR=0.27979969816859374, Volume=nan>
<Data i=69 (2026-09-14 21:00:00) Open=208.311, High=208.346, Low=208.207, Close=208.322, Tickvol=421.0, ATR=0.26974257687083775, Volume=nan>
<Data i=70 (2026-09-14 22:00:00) Open=208.322, High=208.401, Low=208.31, Close=208.314, Tickvol=3453.0, ATR=0.2569752499514928, Volume=nan>
<Data i=71 (2026-09-14 23:00:00) Open=208.313, High=208.482, Low=208.239, Close=208.468, Tickvol=9682.0, ATR=0.2559770178121001, Volume=nan>
<Data i=72 (2026-09-15 00:00:00) Open=208.467, High=208.725, Low=208.439, Close=208.723, Tickvol=22413.0, ATR=0.2581215165398073, Volume=nan>
new date 2026-09-15
<Data i=73 (2026-09-15 01:00:00) Open=208.723, High=208.748, Low=208.63, Close=208.692, Tickvol=7833.0, ATR=0.24811283678696358, Volume=nan>
<Data i=74 (2026-09-15 02:00:00) Open=208.69, High=208.855, Low=208.667, Close=208.786, Tickvol=8519.0, ATR=0.24381906273075105, Volume=nan>
<Data i=75 (2026-09-15 03:00:00) Open=208.781, High=208.788, Low=208.544, Close=208.551, Tickvol=11125.0, ATR=0.24383198682141166, Volume=nan>
<Data i=76 (2026-09-15 04:00:00) Open=208.55, High=208.649, Low=208.517, Close=208.636, Tickvol=10485.0, ATR=0.23584398776273977, Volume=nan>
<Data i=77 (2026-09-15 05:00:00) Open=208.636, High=208.868, Low=208.556, Close=208.718, Tickvol=12192.0, ATR=0.2412837029225429, Volume=nan>
<Data i=78 (2026-09-15 06:00:00) Open=208.719, High=208.724, Low=208.486, Close=208.65, Tickvol=12323.0, ATR=0.24104915271378982, Volume=nan>
<Data i=79 (2026-09-15 07:00:00) Open=208.652, High=208.812, Low=208.514, Close=208.771, Tickvol=14008.0, ATR=0.24511707037709068, Volume=nan>
<Data i=80 (2026-09-15 08:00:00) Open=208.773, High=209.09, Low=208.625, Close=208.842, Tickvol=17362.0, ATR=0.2608229939215844, Volume=nan>
<Data i=81 (2026-09-15 09:00:00) Open=208.842, High=208.873, Low=208.724, Close=208.79, Tickvol=13722.0, ATR=0.25283563721289987, Volume=nan>
<Data i=82 (2026-09-15 10:00:00) Open=208.788, High=208.789, Low=208.558, Close=208.655, Tickvol=11315.0, ATR=0.2513473774119784, Volume=nan>
opening rang high is 209.09
opening rang low is 208.486
<Data i=83 (2026-09-15 11:00:00) Open=208.655, High=208.859, Low=208.607, Close=208.849, Tickvol=13629.0, ATR=0.25139399331112344, Volume=nan>
<Data i=84 (2026-09-15 12:00:00) Open=208.847, High=209.057, Low=208.829, Close=208.925, Tickvol=20199.0, ATR=0.24972299378889892, Volume=nan>
<Data i=85 (2026-09-15 13:00:00) Open=208.928, High=209.179, Low=208.87, Close=209.117, Tickvol=20503.0, ATR=0.25395706566112025, Volume=nan>
<Data i=86 (2026-09-15 14:00:00) Open=209.116, High=209.211, Low=208.99, Close=209.168, Tickvol=20149.0, ATR=0.25160298954246907, Volume=nan>
<Data i=87 (2026-09-15 15:00:00) Open=209.167, High=209.224, Low=208.885, Close=209.04, Tickvol=15461.0, ATR=0.2578456331465783, Volume=nan>
<Data i=88 (2026-09-15 16:00:00) Open=209.04, High=209.072, Low=208.907, Close=209.047, Tickvol=9114.0, ATR=0.2512138022075364, Volume=nan>
<Data i=89 (2026-09-15 17:00:00) Open=209.047, High=209.127, Low=208.993, Close=209.073, Tickvol=7140.0, ATR=0.242841387764142, Volume=nan>
<Data i=90 (2026-09-15 18:00:00) Open=209.071, High=209.106, Low=209.047, Close=209.066, Tickvol=6695.0, ATR=0.2297098600667031, Volume=nan>
<Data i=91 (2026-09-15 19:00:00) Open=209.064, High=209.082, Low=208.969, Close=209.015, Tickvol=6146.0, ATR=0.22137344149051, Volume=nan>
<Data i=92 (2026-09-15 20:00:00) Open=209.011, High=209.036, Low=208.98, Close=209.021, Tickvol=5189.0, ATR=0.20956105281261725, Volume=nan>
<Data i=93 (2026-09-15 21:00:00) Open=208.88, High=209.006, Low=208.872, Close=208.889, Tickvol=1780.0, ATR=0.20523526332599976, Volume=nan>
<Data i=94 (2026-09-15 22:00:00) Open=208.895, High=209.029, Low=208.895, Close=209.019, Tickvol=5661.0, ATR=0.20057560165985594, Volume=nan>
<Data i=95 (2026-09-15 23:00:00) Open=209.018, High=209.342, Low=209.007, Close=209.169, Tickvol=10848.0, ATR=0.21017734439843824, Volume=nan>
<Data i=96 (2026-09-16 00:00:00) Open=209.168, High=209.309, Low=208.982, Close=209.259, Tickvol=24893.0, ATR=0.21852181979854968, Volume=nan>
new date 2026-09-16
<Data i=97 (2026-09-16 01:00:00) Open=209.26, High=209.394, Low=209.168, Close=209.29, Tickvol=8935.0, ATR=0.21905597552722464, Volume=nan>
<Data i=98 (2026-09-16 02:00:00) Open=209.286, High=209.329, Low=209.205, Close=209.259, Tickvol=8177.0, ATR=0.21226626298956539, Volume=nan>
<Data i=99 (2026-09-16 03:00:00) Open=209.258, High=209.467, Low=209.24, Close=209.431, Tickvol=7843.0, ATR=0.21331867277602526, Volume=nan>
<Data i=100 (2026-09-16 04:00:00) Open=209.433, High=209.457, Low=209.381, Close=209.414, Tickvol=4702.0, ATR=0.20351019614916585, Volume=nan>
<Data i=101 (2026-09-16 05:00:00) Open=209.413, High=209.459, Low=209.342, Close=209.361, Tickvol=6679.0, ATR=0.19733089642422472, Volume=nan>
<Data i=102 (2026-09-16 06:00:00) Open=209.354, High=209.407, Low=208.893, Close=208.903, Tickvol=12104.0, ATR=0.21995011810820936, Volume=nan>
<Data i=103 (2026-09-16 07:00:00) Open=208.901, High=209.012, Low=208.715, Close=208.775, Tickvol=12512.0, ATR=0.22545368110047992, Volume=nan>
<Data i=104 (2026-09-16 08:00:00) Open=208.78, High=208.947, Low=208.711, Close=208.937, Tickvol=10916.0, ATR=0.22620698959330207, Volume=nan>
<Data i=105 (2026-09-16 09:00:00) Open=208.933, High=208.976, Low=208.834, Close=208.919, Tickvol=7807.0, ATR=0.22019220462235164, Volume=nan>
<Data i=106 (2026-09-16 10:00:00) Open=208.921, High=209.002, Low=208.887, Close=208.94, Tickvol=5742.0, ATR=0.21267847572075577, Volume=nan>
opening rang high is 209.407
opening rang low is 208.711
<Data i=107 (2026-09-16 11:00:00) Open=208.94, High=208.971, Low=208.563, Close=208.612, Tickvol=13560.0, ATR=0.2266300131692743, Volume=nan>
<Data i=108 (2026-09-16 12:00:00) Open=208.617, High=208.911, Low=208.597, Close=208.881, Tickvol=11160.0, ATR=0.23287072651432564, Volume=nan>
<Data i=109 (2026-09-16 13:00:00) Open=208.885, High=208.987, Low=208.834, Close=208.846, Tickvol=14810.0, ATR=0.22716567462044465, Volume=nan>
<Data i=110 (2026-09-16 14:00:00) Open=208.844, High=208.876, Low=208.634, Close=208.641, Tickvol=14785.0, ATR=0.22822526929041423, Volume=nan>
<Data i=111 (2026-09-16 15:00:00) Open=208.642, High=208.653, Low=208.464, Close=208.512, Tickvol=18391.0, ATR=0.22542346434109842, Volume=nan>
<Data i=112 (2026-09-16 16:00:00) Open=208.51, High=208.745, Low=208.509, Close=208.546, Tickvol=8750.0, ATR=0.2261789311738784, Volume=nan>
<Data i=113 (2026-09-16 17:00:00) Open=208.548, High=208.58, Low=208.447, Close=208.447, Tickvol=7727.0, ATR=0.2195232932328878, Volume=nan>
<Data i=114 (2026-09-16 18:00:00) Open=208.474, High=208.745, Low=208.339, Close=208.639, Tickvol=35650.0, ATR=0.23284305800196767, Volume=nan>
<Data i=115 (2026-09-16 19:00:00) Open=208.64, High=209.055, Low=208.579, Close=209.055, Tickvol=28303.0, ATR=0.25021141100182703, Volume=nan>
<Data i=116 (2026-09-16 20:00:00) Open=209.054, High=209.248, Low=209.003, Close=209.033, Tickvol=7839.0, ATR=0.24983916735883974, Volume=nan>
<Data i=117 (2026-09-16 21:00:00) Open=208.863, High=209.071, Low=208.863, Close=208.975, Tickvol=1106.0, ATR=0.2468506554046368, Volume=nan>
<Data i=118 (2026-09-16 22:00:00) Open=208.975, High=209.096, Low=208.974, Close=209.061, Tickvol=4885.0, ATR=0.23793275144716372, Volume=nan>
<Data i=119 (2026-09-16 23:00:00) Open=209.062, High=209.09, Low=208.788, Close=208.807, Tickvol=9886.0, ATR=0.24250898348665148, Volume=nan>

GridPlot(id='p1958', ...)

In [12]:
import pandas as pd
import datetime as dt
from ta.volatility import AverageTrueRange
from backtesting import Backtest, Strategy

class OpeningRangeBreakout(Strategy):
    # variables
    range_to_consider = 5

    # fixed variables
    close_range_hour = 10
    open_range_hour = close_range_hour - range_to_consider

    def init(self):
        self.current_day = None
        self.opening_range_high = None
        self.opening_range_low = None

    def reset_range(self, day):
        self.current_day = day
        self.opening_range_high = None
        self.opening_range_low = None

    def next(self):
        t = self.data.index[-1]
        current_bar_date = self.data.index[-1].date()

        if (self.current_day != current_bar_date):
            self.reset_range(current_bar_date)
            print(f"new date {current_bar_date}")

        if self.open_range_hour < t.time().hour and t.time().hour <= self.close_range_hour:
            if self.opening_range_high is not None:
                self.opening_range_high = max(self.opening_range_high, self.data.High[-1])
            else:
                self.opening_range_high = self.data.High[-1]

            if self.opening_range_low is not None:
                    self.opening_range_low = min(self.opening_range_low, self.data.Low[-1])
            else:
                self.opening_range_low = self.data.Low[-1]

            if t.time().hour < self.close_range_hour:
                return

        if t.time().hour == self.close_range_hour:
            print(f"opening rang high is {self.opening_range_high}")
            print(f"opening rang low is {self.opening_range_low}")

        if t.time().hour > self.close_range_hour and self.opening_range_high is not None and self.opening_range_low is not None:
            if not self.position:
                if self.data.Open[-1] < self.opening_range_high and self.data.Close[-1] > self.opening_range_high:
                    print('Go long')
                    order = self.buy(size = 200)


df = pd.read_csv("./Trading Data/GBPJPY_H1.csv",sep=',', parse_dates=['Date'], index_col='Date')
df = df.loc['2026-09-1' : '2026-09-16']

indicator_atr = AverageTrueRange(df['High'], df['Low'], df['Close'], window=14)
df['ATR'] = indicator_atr._atr

bt = Backtest(df, OpeningRangeBreakout, cash = 25_000, finalize_trades=True)

stats = bt.run()

bt.plot()

print(stats)

new date 2026-09-01
opening rang high is 216.736
opening rang low is 216.45
Go long
new date 2026-09-02
opening rang high is 215.886
opening rang low is 215.243
new date 2026-09-03
opening rang high is 212.337
opening rang low is 210.771
new date 2026-09-04
opening rang high is 211.815
opening rang low is 211.369
new date 2026-09-06
new date 2026-09-07
opening rang high is 210.849
opening rang low is 208.639
new date 2026-09-08
opening rang high is 208.677
opening rang low is 207.636
Go long
Go long
new date 2026-09-09
opening rang high is 208.155
opening rang low is 207.38
new date 2026-09-10
opening rang high is 208.709
opening rang low is 207.833
new date 2026-09-11
opening rang high is 208.563
opening rang low is 207.908
new date 2026-09-13
new date 2026-09-14
opening rang high is 208.625
opening rang low is 207.876
Go long
new date 2026-09-15
opening rang high is 209.09
opening rang low is 208.486
Go long
Go long
new date 2026-09-16
opening rang high is 209.407
opening rang low is 208.711

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=14: Broker canceled the order due to insufficient margin (equity=25000.00, margin_available=25000.00).
  warnings.warn(
c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=132: Broker canceled the order due to insufficient margin (equity=25000.00, margin_available=25000.00).
  warnings.warn(
c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=135: Broker canceled the order due to insufficient margin (equity=25000.00, margin_available=25000.00).
  warnings.warn(
c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=230: Broker canceled the order due to insufficient margin (equity=25000.00, margin_available=25000.00).
  warnings.warn(
c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=254: Broker canceled the order due to insufficient margin (equity=25000.00, margin_available=25000.00).
  warnings.warn(
c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=264: Broker canceled the order due to insufficient margin (equity=25000.00, margin_available=25000.00).
  warnings.warn(

Start                     2026-09-01 00:00:00
End                       2026-09-16 23:00:00
Duration                     15 days 23:00:00
Exposure Time [%]                         0.0
Equity Final [$]                      25000.0
Equity Peak [$]                       25000.0
Return [%]                                0.0
Buy & Hold Return [%]                -3.58274
Return (Ann.) [%]                         0.0
Volatility (Ann.) [%]                     0.0
CAGR [%]                                  0.0
Sharpe Ratio                               --
Sortino Ratio                              --
Calmar Ratio                               --
Alpha [%]                                 0.0
Beta                                      0.0
Max. Drawdown [%]                        -0.0
Avg. Drawdown [%]                          --
Max. Drawdown Duration                     --
Avg. Drawdown Duration                     --
# Trades                                    0
Win Rate [%]                               --
Best Trade [%]                             --
Worst Trade [%]                            --
Avg. Trade [%]                             --
Max. Trade Duration                        --
Avg. Trade Duration                        --
Profit Factor                              --
Expectancy [%]                             --
SQN                                        --
Kelly Criterion                            --
_strategy                 OpeningRangeBrea...
_equity_curve                             ...
_trades                   Empty DataFrame
...
dtype: object

In [174]:
import pandas as pd
import datetime as dt
from ta.volatility import AverageTrueRange
from backtesting import Backtest, Strategy

class OpeningRangeBreakout(Strategy):
    # variables
    range_to_consider = 3
    tp_multiple = 5.5
    stop_trade_hour = 18
    close_range_hour = 8

    # fixed variables
    my_equity = 10000
    max_leverage = 4
    risk_percent = 0.01
    open_range_hour = close_range_hour - range_to_consider

    def init(self):
        self.current_day = None
        self.opening_range_high = None
        self.opening_range_low = None

    def reset_range(self, day):
        self.current_day = day
        self.current_day_position_taked = False
        self.opening_range_high = None
        self.opening_range_low = None

    def get_position_size(self, entry_price: float, stop_price : float) -> int:
        per_share_risk = abs(entry_price - stop_price)
        print(per_share_risk)
        if per_share_risk == 0:
            return 0

        share_by_risk = (self.risk_percent * self.equity) / entry_price

        share_by_leverage = (self.max_leverage * self.equity) / entry_price
        print(f"share_by_risk = {share_by_risk} & share_by_leverage = {share_by_leverage}")

        return int(min(share_by_risk, share_by_leverage))

    def next(self):
        t = self.data.index[-1]
        current_bar_date = self.data.index[-1].date()

        if (self.current_day != current_bar_date):
            self.reset_range(current_bar_date)
            # print(f"new date {current_bar_date}")

        if self.open_range_hour < t.time().hour and t.time().hour <= self.close_range_hour:
            if self.opening_range_high is not None:
                self.opening_range_high = max(self.opening_range_high, self.data.High[-1])
            else:
                self.opening_range_high = self.data.High[-1]

            if self.opening_range_low is not None:
                    self.opening_range_low = min(self.opening_range_low, self.data.Low[-1])
            else:
                self.opening_range_low = self.data.Low[-1]

            if t.time().hour < self.close_range_hour:
                return

        if t.time().hour > self.close_range_hour and self.opening_range_high is not None and self.opening_range_low is not None:
            c_long = self.data.Open[-1] < self.opening_range_high and self.data.Close[-1] > self.opening_range_high
            c_short = self.data.Open[-1] > self.opening_range_low and self.data.Close[-1] < self.opening_range_low
            
            c2 = (self.opening_range_high - self.opening_range_low) < self.data['ATR'][-1] * 2.5
            c3 = (self.opening_range_high - self.opening_range_low) > self.data['ATR'][-1] * 1.0
            c4 = t.time().hour < self.stop_trade_hour

            if not self.current_day_position_taked:
                if c_long and c2 and c3 and c4:
                    planned_entry_price = self.data.Close[-1]
                    tp_price = self.opening_range_high + (planned_entry_price - self.opening_range_low) * self.tp_multiple
                    sl_price = self.opening_range_low
                    per_share_risk = abs(planned_entry_price - sl_price)
                    position_size = int((self.risk_percent * self.my_equity) / per_share_risk)

                    print(f'Go long tp = {tp_price} sl = {sl_price} position size = {position_size}')
                    order = self.buy(size = position_size, tp=tp_price, sl=sl_price)
                    self.current_day_position_taked = True

                # if c_short and c2 and c3 and c4:
                #     planned_entry_price = self.data.Close[-1]
                #     sl_price = self.opening_range_high
                #     per_share_risk = abs(planned_entry_price - sl_price)
                #     tp_price = self.opening_range_low - per_share_risk * self.tp_multiple
                #     position_size = int((self.risk_percent * self.my_equity) / per_share_risk)

                #     print(f'Go short tp = {tp_price} sl = {sl_price} position size = {position_size}')
                #     order = self.sell(size = position_size, tp=tp_price, sl=sl_price)
                #     self.current_day_position_taked = True

        # if self.position:
        # print(self.trades)
        # print(self.position.)


def per_share_commission(size, price):
    return abs(size) * 0.0005

timezone = "Europe/London"

df = pd.read_csv("./Trading Data/GBPJPY_H1.csv",sep=',', parse_dates=['Date'], index_col='Date')
df.index = pd.to_datetime(df.index, utc=True).tz_convert(timezone)
df = df.loc['2020-01-01' : '2026-9-16']

indicator_atr = AverageTrueRange(df['High'], df['Low'], df['Close'], window=14)
df['ATR'] = indicator_atr._atr

bt = Backtest(df, OpeningRangeBreakout, margin=0.02, finalize_trades=True)

stats = bt.run()

print(stats)

bt.plot()

Go long tp = 146.038 sl = 141.114 position size = 123
Go long tp = 147.6005000000001 sl = 142.063 position size = 115
Go long tp = 146.08499999999992 sl = 142.971 position size = 208
Go long tp = 147.07900000000006 sl = 143.237 position size = 165
Go long tp = 145.3385 sl = 142.864 position size = 262
Go long tp = 145.81849999999997 sl = 142.894 position size = 207
Go long tp = 147.38700000000006 sl = 143.386 position size = 153
Go long tp = 146.969 sl = 141.255 position size = 106
Go long tp = 144.69450000000006 sl = 141.32 position size = 186
Go long tp = 144.26750000000013 sl = 141.724 position size = 240
Go long tp = 147.13749999999987 sl = 142.139 position size = 118
Go long tp = 146.28250000000003 sl = 142.314 position size = 155
Go long tp = 146.01049999999992 sl = 142.888 position size = 203
Go long tp = 148.0150000000001 sl = 143.779 position size = 145
Go long tp = 141.36549999999994 sl = 137.247 position size = 157
Go long tp = 144.41599999999997 sl = 135.528 position size = 71
Go long tp = 135.9595 sl = 125.071 position size = 57
Go long tp = 135.86050000000006 sl = 127.759 position size = 79
Go long tp = 136.17300000000006 sl = 128.088 position size = 79
Go long tp = 143.5645 sl = 131.43 position size = 51
Go long tp = 141.41549999999995 sl = 130.671 position size = 58
Go long tp = 139.7984999999999 sl = 132.15 position size = 83
Go long tp = 138.4035 sl = 133.147 position size = 121
Go long tp = 137.75999999999993 sl = 133.216 position size = 136
Go long tp = 140.52449999999993 sl = 133.428 position size = 90
Go long tp = 139.02700000000013 sl = 133.724 position size = 117
Go long tp = 138.56900000000013 sl = 134.634 position size = 161
Go long tp = 136.66999999999996 sl = 135.02 position size = 384
Go long tp = 138.42550000000006 sl = 132.14 position size = 98
Go long tp = 135.24750000000006 sl = 132.535 position size = 238
Go long tp = 135.11299999999997 sl = 132.662 position size = 263
Go long tp = 133.57450000000009 sl = 131.664 position size = 338
Go long tp = 133.22750000000008 sl = 130.136 position size = 203
Go long tp = 132.64200000000005 sl = 129.577 position size = 199
Go long tp = 134.46800000000002 sl = 131.217 position size = 190
Go long tp = 132.58300000000006 sl = 130.988 position size = 396
Go long tp = 136.5810000000001 sl = 132.118 position size = 139
Go long tp = 135.40300000000002 sl = 132.051 position size = 186
Go long tp = 135.42950000000008 sl = 131.933 position size = 181
Go long tp = 137.21800000000005 sl = 133.082 position size = 152
Go long tp = 140.01850000000002 sl = 136.5 position size = 182
Go long tp = 142.92049999999995 sl = 136.346 position size = 90
Go long tp = 140.44949999999994 sl = 134.624 position size = 110
Go long tp = 140.247 sl = 133.498 position size = 92
Go long tp = 137.86749999999995 sl = 132.133 position size = 110
Go long tp = 136.41650000000004 sl = 132.822 position size = 170
Go long tp = 139.49300000000005 sl = 132.015 position size = 79
Go long tp = 137.05249999999995 sl = 132.981 position size = 150
Go long tp = 136.22350000000012 sl = 134.136 position size = 307
Go long tp = 136.95900000000012 sl = 134.112 position size = 216
Go long tp = 137.6069999999999 sl = 134.853 position size = 219
Go long tp = 137.62899999999996 sl = 135.429 position size = 285
Go long tp = 136.6950000000001 sl = 134.279 position size = 264
Go long tp = 136.48050000000006 sl = 134.058 position size = 261
Go long tp = 137.91649999999998 sl = 134.368 position size = 176
Go long tp = 138.0745 sl = 135.14 position size = 220
Go long tp = 137.59150000000005 sl = 135.564 position size = 315
Go long tp = 137.99599999999992 sl = 135.673 position size = 277
Go long tp = 139.15550000000002 sl = 136.071 position size = 207
Go long tp = 140.23450000000014 sl = 136.884 position size = 184
Go long tp = 142.41600000000005 sl = 138.089 position size = 144
Go long tp = 141.0414999999999 sl = 138.097 position size = 219
Go long tp = 140.4675000000001 sl = 138.636 position size = 353
Go long tp = 141.9254999999999 sl = 138.954 position size = 216
Go long tp = 141.46949999999998 sl = 139.332 position size = 284
Go long tp = 142.26299999999998 sl = 139.338 position size = 212
Go long tp = 140.895 sl = 138.65 position size = 279
Go long tp = 141.08000000000004 sl = 138.563 position size = 249
Go long tp = 141.07750000000001 sl = 138.518 position size = 243
Go long tp = 142.64500000000004 sl = 138.745 position size = 159
Go long tp = 142.62649999999996 sl = 139.633 position size = 200
Go long tp = 141.983 sl = 139.931 position size = 316
Go long tp = 142.48499999999996 sl = 140.761 position size = 375
Go long tp = 145.31799999999998 sl = 141.584 position size = 166
Go long tp = 144.85250000000002 sl = 140.697 position size = 149
Go long tp = 141.2569999999999 sl = 136.734 position size = 143
Go long tp = 138.2015 sl = 135.836 position size = 271
Go long tp = 138.82350000000002 sl = 135.787 position size = 209
Go long tp = 139.35699999999997 sl = 135.609 position size = 160
Go long tp = 138.59049999999993 sl = 133.139 position size = 114
Go long tp = 137.20049999999998 sl = 133.603 position size = 176
Go long tp = 138.75349999999997 sl = 134.382 position size = 141
Go long tp = 138.6545 sl = 135.624 position size = 207
Go long tp = 138.858 sl = 135.174 position size = 173
Go long tp = 141.519 sl = 135.851 position size = 112
Go long tp = 139.95000000000005 sl = 136.224 position size = 166
Go long tp = 139.62650000000002 sl = 137.053 position size = 246
Go long tp = 139.73100000000005 sl = 137.331 position size = 257
Go long tp = 140.37050000000002 sl = 135.66 position size = 134
Go long tp = 139.8635000000001 sl = 135.635 position size = 153
Go long tp = 139.38650000000007 sl = 136.327 position size = 206
Go long tp = 139.74550000000005 sl = 136.597 position size = 204
Go long tp = 139.74850000000015 sl = 136.295 position size = 180
Go long tp = 139.8745 sl = 134.419 position size = 112
Go long tp = 138.14600000000002 sl = 134.869 position size = 197
Go long tp = 142.87049999999988 sl = 136.079 position size = 87
Go long tp = 145.73950000000013 sl = 138.283 position size = 80
Go long tp = 142.51700000000005 sl = 137.844 position size = 129
Go long tp = 140.86399999999995 sl = 137.812 position size = 210
Go long tp = 141.2580000000001 sl = 137.243 position size = 154
Go long tp = 140.12899999999996 sl = 137.601 position size = 251
Go long tp = 142.84550000000002 sl = 139.17 position size = 164
Go long tp = 142.7530000000001 sl = 138.533 position size = 149
Go long tp = 141.91799999999995 sl = 139.413 position size = 259
Go long tp = 142.71050000000008 sl = 139.653 position size = 198
Go long tp = 143.85649999999995 sl = 139.44 position size = 141
Go long tp = 141.53250000000008 sl = 138.665 position size = 225
Go long tp = 142.9575000000001 sl = 138.277 position size = 134
Go long tp = 143.38899999999995 sl = 139.162 position size = 151
Go long tp = 142.4685 sl = 139.927 position size = 239
Go long tp = 143.0969999999999 sl = 138.621 position size = 134
Go long tp = 144.6945 sl = 140.256 position size = 145
Go long tp = 142.05249999999995 sl = 139.791 position size = 268
Go long tp = 144.36949999999996 sl = 140.496 position size = 162
Go long tp = 143.47349999999994 sl = 139.866 position size = 177
Go long tp = 143.13950000000006 sl = 140.887 position size = 283
Go long tp = 142.7945000000001 sl = 140.444 position size = 263
Go long tp = 144.47449999999998 sl = 141.705 position size = 227
Go long tp = 143.04599999999988 sl = 141.341 position size = 378
Go long tp = 144.44000000000005 sl = 141.644 position size = 223
Go long tp = 144.27150000000012 sl = 141.277 position size = 207
Go long tp = 144.5195 sl = 142.358 position size = 294
Go long tp = 145.132 sl = 142.227 position size = 218
Go long tp = 145.51149999999996 sl = 142.991 position size = 255
Go long tp = 148.57800000000003 sl = 142.834 position size = 101
Go long tp = 147.801 sl = 144.406 position size = 177
Go long tp = 146.85000000000014 sl = 144.557 position size = 276
Go long tp = 149.1559999999999 sl = 145.948 position size = 196
Go long tp = 149.74550000000008 sl = 146.706 position size = 206
Go long tp = 151.14899999999992 sl = 147.281 position size = 159
Go long tp = 150.15700000000004 sl = 147.802 position size = 274
Go long tp = 151.07699999999983 sl = 147.741 position size = 190
Go long tp = 154.12900000000002 sl = 147.399 position size = 93
Go long tp = 152.5919999999999 sl = 148.168 position size = 136
Go long tp = 152.20600000000007 sl = 148.941 position size = 196
Go long tp = 152.04 sl = 149.369 position size = 240
Go long tp = 152.7134999999999 sl = 149.68 position size = 211
Go long tp = 153.14899999999997 sl = 150.836 position size = 280
Go long tp = 152.61249999999998 sl = 150.428 position size = 294
Go long tp = 152.44849999999994 sl = 148.523 position size = 157
Go long tp = 153.33700000000005 sl = 148.968 position size = 144
Go long tp = 154.52450000000002 sl = 151.331 position size = 197
Go long tp = 153.6515 sl = 152.06 position size = 401
Go long tp = 154.7525 sl = 152.288 position size = 258
Go long tp = 155.47499999999994 sl = 152.881 position size = 234
Go long tp = 154.47449999999992 sl = 149.586 position size = 128
Go long tp = 154.45749999999998 sl = 149.752 position size = 134
Go long tp = 152.88200000000006 sl = 149.381 position size = 179
Go long tp = 153.22749999999996 sl = 150.119 position size = 207
Go long tp = 152.476 sl = 149.705 position size = 230
Go long tp = 152.70700000000008 sl = 150.225 position size = 245
Go long tp = 153.53649999999993 sl = 151.023 position size = 248
Go long tp = 156.20999999999998 sl = 153.636 position size = 240
Go long tp = 155.66950000000003 sl = 153.721 position size = 321
Go long tp = 156.26799999999997 sl = 153.839 position size = 263
Go long tp = 157.08099999999996 sl = 154.008 position size = 203
Go long tp = 156.62150000000008 sl = 153.861 position size = 225
Go long tp = 159.2855 sl = 153.879 position size = 108
Go long tp = 157.64200000000002 sl = 155.031 position size = 239
Go long tp = 157.42450000000002 sl = 155.306 position size = 280
Go long tp = 157.31399999999996 sl = 155.275 position size = 312
Go long tp = 156.836 sl = 154.553 position size = 279
Go long tp = 157.3055000000001 sl = 154.914 position size = 259
Go long tp = 160.09649999999988 sl = 154.127 position size = 99
Go long tp = 157.9755 sl = 154.566 position size = 178
Go long tp = 159.13999999999993 sl = 151.476 position size = 79
Go long tp = 155.85399999999998 sl = 153.286 position size = 251
Go long tp = 155.558 sl = 152.697 position size = 221
Go long tp = 156.58450000000005 sl = 153.434 position size = 203
Go long tp = 156.18850000000015 sl = 152.503 position size = 169
Go long tp = 153.6545000000001 sl = 151.438 position size = 281
Go long tp = 156.56000000000003 sl = 152.599 position size = 161
Go long tp = 155.774 sl = 152.698 position size = 204
Go long tp = 157.40899999999993 sl = 151.603 position size = 107
Go long tp = 156.3485 sl = 151.816 position size = 133
Go long tp = 152.5575000000001 sl = 149.279 position size = 196
Go long tp = 154.11050000000003 sl = 149.284 position size = 132
Go long tp = 153.28600000000012 sl = 151.534 position size = 367
Go long tp = 155.732 sl = 151.422 position size = 140
Go long tp = 155.64699999999993 sl = 152.174 position size = 181
Go long tp = 155.64499999999998 sl = 152.846 position size = 230
Go long tp = 155.34600000000006 sl = 151.809 position size = 174
Go long tp = 156.0795 sl = 152.222 position size = 161
Go long tp = 155.05800000000005 sl = 152.69 position size = 257
Go long tp = 154.25999999999988 sl = 152.973 position size = 490
Go long tp = 153.65649999999994 sl = 151.293 position size = 272
Go long tp = 152.35299999999995 sl = 150.512 position size = 337
Go long tp = 152.38449999999992 sl = 149.181 position size = 198
Go long tp = 153.07549999999998 sl = 149.888 position size = 193
Go long tp = 152.2269999999999 sl = 150.442 position size = 354
Go long tp = 152.18000000000004 sl = 151.023 position size = 555
Go long tp = 154.50649999999993 sl = 151.477 position size = 198
Go long tp = 153.58549999999994 sl = 151.417 position size = 286
Go long tp = 153.938 sl = 151.934 position size = 318
Go long tp = 153.38600000000002 sl = 150.999 position size = 261
Go long tp = 153.27249999999998 sl = 151.472 position size = 358
Go long tp = 152.93549999999993 sl = 149.198 position size = 166
Go long tp = 153.44349999999997 sl = 149.77 position size = 168
Go long tp = 155.96800000000007 sl = 151.172 position size = 125
Go long tp = 153.34400000000005 sl = 150.248 position size = 204
Go long tp = 154.0605 sl = 149.226 position size = 131
Go long tp = 153.74999999999994 sl = 150.241 position size = 185
Go long tp = 153.78250000000014 sl = 150.974 position size = 230
Go long tp = 154.38649999999993 sl = 151.138 position size = 194
Go long tp = 154.2575000000001 sl = 152.04 position size = 277
Go long tp = 157.7940000000001 sl = 153.659 position size = 153
Go long tp = 157.8219999999999 sl = 153.681 position size = 152
Go long tp = 157.59249999999992 sl = 154.299 position size = 194
Go long tp = 158.0385 sl = 155.041 position size = 209
Go long tp = 160.99950000000013 sl = 156.927 position size = 147
Go long tp = 160.14150000000006 sl = 156.712 position size = 185
Go long tp = 159.80449999999993 sl = 155.913 position size = 166
Go long tp = 158.6155 sl = 156.48 position size = 300
Go long tp = 159.18300000000005 sl = 154.73 position size = 143
Go long tp = 157.33650000000006 sl = 154.959 position size = 265
Go long tp = 156.923 sl = 152.703 position size = 151
Go long tp = 155.75349999999997 sl = 153.037 position size = 230
Go long tp = 157.39049999999997 sl = 152.941 position size = 136
Go long tp = 155.6545 sl = 152.751 position size = 217
Go long tp = 155.54950000000002 sl = 153.94 position size = 398
Go long tp = 157.34199999999987 sl = 153.121 position size = 148
Go long tp = 155.8205000000001 sl = 150.684 position size = 125
Go long tp = 153.64750000000015 sl = 150.182 position size = 184
Go long tp = 153.76299999999998 sl = 149.493 position size = 150
Go long tp = 153.20349999999996 sl = 150.001 position size = 202
Go long tp = 153.33649999999994 sl = 150.078 position size = 191
Go long tp = 152.2405 sl = 149.955 position size = 275
Go long tp = 158.751 sl = 151.154 position size = 79
Go long tp = 152.46350000000007 sl = 149.655 position size = 228
Go long tp = 152.86649999999997 sl = 150.109 position size = 234
Go long tp = 155.31999999999996 sl = 153.132 position size = 290
Go long tp = 156.93399999999997 sl = 153.302 position size = 173
Go long tp = 155.59100000000004 sl = 154.215 position size = 462
Go long tp = 155.78649999999996 sl = 154.139 position size = 392
Go long tp = 156.78899999999996 sl = 154.952 position size = 352
Go long tp = 159.0765000000001 sl = 155.326 position size = 158
Go long tp = 159.65949999999992 sl = 156.859 position size = 219
Go long tp = 160.57650000000012 sl = 156.426 position size = 153
Go long tp = 159.57799999999992 sl = 157.173 position size = 256
Go long tp = 158.93349999999998 sl = 157.043 position size = 343
Go long tp = 158.828 sl = 155.99 position size = 221
Go long tp = 158.41450000000003 sl = 155.396 position size = 199
Go long tp = 156.423 sl = 153.279 position size = 202
Go long tp = 156.86599999999999 sl = 153.783 position size = 207
Go long tp = 157.63100000000003 sl = 153.817 position size = 169
Go long tp = 157.17649999999998 sl = 154.639 position size = 255
Go long tp = 156.55950000000007 sl = 154.976 position size = 404
Go long tp = 157.81400000000008 sl = 155.148 position size = 238
Go long tp = 157.953 sl = 156.041 position size = 322
Go long tp = 159.47399999999993 sl = 156.279 position size = 193
Go long tp = 160.64700000000005 sl = 156.426 position size = 140
Go long tp = 158.67849999999993 sl = 155.568 position size = 208
Go long tp = 158.77299999999994 sl = 154.151 position size = 138
Go long tp = 158.40299999999996 sl = 154.278 position size = 146
Go long tp = 157.325 sl = 152.811 position size = 138
Go long tp = 155.4215 sl = 150.975 position size = 145
Go long tp = 155.27550000000008 sl = 151.791 position size = 177
Go long tp = 156.93149999999997 sl = 152.5 position size = 139
Go long tp = 156.57349999999997 sl = 153.287 position size = 191
Go long tp = 157.7599999999999 sl = 154.247 position size = 176
Go long tp = 160.59399999999994 sl = 156.025 position size = 135
Go long tp = 159.76449999999997 sl = 156.732 position size = 198
Go long tp = 164.94500000000005 sl = 159.986 position size = 128
Go long tp = 164.57000000000008 sl = 159.47 position size = 123
Go long tp = 164.51000000000016 sl = 161.67 position size = 221
Go long tp = 167.22299999999993 sl = 164.633 position size = 248
Go long tp = 173.18899999999996 sl = 166.157 position size = 87
Go long tp = 171.2619999999999 sl = 167.085 position size = 149
Go long tp = 166.95299999999997 sl = 163.048 position size = 161
Go long tp = 165.69300000000004 sl = 162.173 position size = 183
Go long tp = 165.9255 sl = 160.726 position size = 120
Go long tp = 166.8959999999999 sl = 160.205 position size = 91
Go long tp = 164.63749999999993 sl = 156.794 position size = 78
Go long tp = 164.86200000000008 sl = 157.426 position size = 85
Go long tp = 165.53549999999996 sl = 159.001 position size = 98
Go long tp = 163.99950000000004 sl = 158.968 position size = 128
Go long tp = 165.59450000000004 sl = 159.152 position size = 100
Go long tp = 163.49700000000004 sl = 160.503 position size = 209
Go long tp = 165.08999999999992 sl = 160.936 position size = 150
Go long tp = 173.644 sl = 165.278 position size = 72
Go long tp = 172.0365 sl = 167.198 position size = 127
Go long tp = 167.17099999999996 sl = 161.722 position size = 112
Go long tp = 174.17849999999987 sl = 164.097 position size = 63
Go long tp = 170.689 sl = 164.489 position size = 102
Go long tp = 170.0075 sl = 164.8 position size = 123
Go long tp = 167.84549999999996 sl = 163.255 position size = 140
Go long tp = 169.6050000000001 sl = 163.367 position size = 103
Go long tp = 167.7089999999999 sl = 162.008 position size = 109
Go long tp = 171.3535 sl = 161.99 position size = 65
Go long tp = 168.72100000000015 sl = 162.932 position size = 109
Go long tp = 172.13499999999996 sl = 164.247 position size = 77
Go long tp = 171.11899999999994 sl = 164.806 position size = 99
Go long tp = 168.88850000000002 sl = 163.109 position size = 104
Go long tp = 167.91500000000005 sl = 164.873 position size = 209
Go long tp = 166.03200000000012 sl = 161.063 position size = 126
Go long tp = 165.976 sl = 159.432 position size = 97
Go long tp = 168.42450000000008 sl = 161.635 position size = 94
Go long tp = 168.077 sl = 162.503 position size = 115
Go long tp = 167.56849999999997 sl = 162.692 position size = 128
Go long tp = 164.72500000000014 sl = 162.974 position size = 367
Go long tp = 164.68250000000012 sl = 160.569 position size = 156
Go long tp = 166.87449999999995 sl = 162.471 position size = 145
Go long tp = 166.1255 sl = 162.274 position size = 164
Go long tp = 166.98450000000003 sl = 160.795 position size = 102
Go long tp = 164.83499999999992 sl = 161.383 position size = 174
Go long tp = 164.82949999999997 sl = 161.786 position size = 207
Go long tp = 165.11049999999992 sl = 161.872 position size = 189
Go long tp = 165.85049999999995 sl = 160.655 position size = 122
Go long tp = 170.33700000000013 sl = 165.027 position size = 119
Go long tp = 165.533 sl = 163.13 position size = 263
Go long tp = 171.09950000000003 sl = 151.66 position size = 33
Go long tp = 165.27400000000003 sl = 155.644 position size = 62
Go long tp = 169.68149999999997 sl = 160.322 position size = 66
Go long tp = 169.15200000000002 sl = 161.24 position size = 78
Go long tp = 166.13399999999996 sl = 160.292 position size = 109
Go long tp = 168.59099999999992 sl = 160.078 position size = 73
Go long tp = 166.71549999999996 sl = 162.308 position size = 142
Go long tp = 174.26899999999995 sl = 166.973 position size = 88

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\_plotting.py:141: UserWarning: Data contains too many candlesticks to plot; downsampling to '8h'. See `Backtest.plot(resample=...)`
  warnings.warn(f"Data contains too many candlesticks to plot; downsampling to {freq!r}. "
c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning: no explicit representation of timezones available for np.datetime64
  return convert(array.astype("datetime64[us]"))

GridPlot(id='p12891', ...)

In [2]:
import pandas as pd
import datetime as dt
from ta.volatility import AverageTrueRange
from backtesting import Backtest, Strategy

class OpeningRangeBreakout(Strategy):
    # variables
    range_to_consider = 3
    tp_multiple = 5.5
    stop_trade_hour = 18
    close_range_hour = 8

    # fixed variables
    my_equity = 10000
    max_leverage = 4
    risk_percent = 0.01
    open_range_hour = close_range_hour - range_to_consider

    def init(self):
        self.current_day = None
        self.opening_range_high = None
        self.opening_range_low = None

    def reset_range(self, day):
        self.current_day = day
        self.current_day_position_taked = False
        self.opening_range_high = None
        self.opening_range_low = None

    def get_position_size(self, entry_price: float, stop_price : float) -> int:
        per_share_risk = abs(entry_price - stop_price)
        print(per_share_risk)
        if per_share_risk == 0:
            return 0

        share_by_risk = (self.risk_percent * self.equity) / entry_price

        share_by_leverage = (self.max_leverage * self.equity) / entry_price
        print(f"share_by_risk = {share_by_risk} & share_by_leverage = {share_by_leverage}")

        return int(min(share_by_risk, share_by_leverage))

    def next(self):
        t = self.data.index[-1]
        current_bar_date = self.data.index[-1].date()

        if (self.current_day != current_bar_date):
            self.reset_range(current_bar_date)
            # print(f"new date {current_bar_date}")

        if self.open_range_hour < t.time().hour and t.time().hour <= self.close_range_hour:
            if self.opening_range_high is not None:
                self.opening_range_high = max(self.opening_range_high, self.data.High[-1])
            else:
                self.opening_range_high = self.data.High[-1]

            if self.opening_range_low is not None:
                    self.opening_range_low = min(self.opening_range_low, self.data.Low[-1])
            else:
                self.opening_range_low = self.data.Low[-1]

            if t.time().hour < self.close_range_hour:
                return

        if t.time().hour > self.close_range_hour and self.opening_range_high is not None and self.opening_range_low is not None:
            c_long = self.data.Open[-1] < self.opening_range_high and self.data.Close[-1] > self.opening_range_high
            c_short = self.data.Open[-1] > self.opening_range_low and self.data.Close[-1] < self.opening_range_low
            
            c2 = (self.opening_range_high - self.opening_range_low) < self.data['ATR'][-1] * 2.5
            c3 = (self.opening_range_high - self.opening_range_low) > self.data['ATR'][-1] * 1.0
            c4 = t.time().hour < self.stop_trade_hour

            if not self.current_day_position_taked:
                if c_long and c2 and c3 and c4:
                    planned_entry_price = self.data.Close[-1]
                    tp_price = self.opening_range_high + (planned_entry_price - self.opening_range_low) * self.tp_multiple
                    sl_price = self.opening_range_low
                    per_share_risk = abs(planned_entry_price - sl_price)
                    position_size = int((self.risk_percent * self.my_equity) / per_share_risk)

                    # print(f'Go long tp = {tp_price} sl = {sl_price} position size = {position_size}')
                    order = self.buy(size = position_size, tp=tp_price, sl=sl_price)
                    self.current_day_position_taked = True

                # if c_short and c2 and c3 and c4:
                #     planned_entry_price = self.data.Close[-1]
                #     sl_price = self.opening_range_high
                #     per_share_risk = abs(planned_entry_price - sl_price)
                #     tp_price = self.opening_range_low - per_share_risk * self.tp_multiple
                #     position_size = int((self.risk_percent * self.my_equity) / per_share_risk)

                #     # print(f'Go short tp = {tp_price} sl = {sl_price} position size = {position_size}')
                #     order = self.sell(size = position_size, tp=tp_price, sl=sl_price)
                #     self.current_day_position_taked = True

        # if self.position:
        # print(self.trades)
        # print(self.position.)


def per_share_commission(size, price):
    return abs(size) * 0.0005

timezone = "Europe/London"

df = pd.read_csv("./Trading Data/GBPJPY_H1.csv",sep=',', parse_dates=['Date'], index_col='Date')
df.index = pd.to_datetime(df.index, utc=True).tz_convert(timezone)
df = df.loc['2020-01-01' : '2026-9-16']

indicator_atr = AverageTrueRange(df['High'], df['Low'], df['Close'], window=14)
df['ATR'] = indicator_atr._atr

bt = Backtest(df, OpeningRangeBreakout, margin=0.02, finalize_trades=True)

stats = bt.run()

print(stats)

bt.plot()

Start                     2020-01-01 22:00...
End                       2026-09-16 23:00...
Duration                   2450 days 00:00:00
Exposure Time [%]                    81.51317
Equity Final [$]                   45102.9225
Equity Peak [$]                     46708.217
Return [%]                          351.02922
Buy & Hold Return [%]                 45.2226
Return (Ann.) [%]                    19.84416
Volatility (Ann.) [%]                21.51788
CAGR [%]                             25.17855
Sharpe Ratio                          0.92222
Sortino Ratio                         1.92397
Calmar Ratio                          1.07595
Alpha [%]                           300.38141
Beta                                  1.11997
Max. Drawdown [%]                   -18.44345
Avg. Drawdown [%]                    -1.38644
Max. Drawdown Duration      240 days 09:00:00
Avg. Drawdown Duration        8 days 00:00:00
# Trades                                  796
Win Rate [%]                         23.11558
Best Trade [%]                       10.61872
Worst Trade [%]                      -1.46273
Avg. Trade [%]                        0.18526
Max. Trade Duration         199 days 23:00:00
Avg. Trade Duration           5 days 20:00:00
Profit Factor                         1.65381
Expectancy [%]                        0.19237
SQN                                   4.69026
Kelly Criterion                       0.08378
_strategy                 OpeningRangeBrea...
_equity_curve                             ...
_trades                        Size  Entry...
dtype: object

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\_plotting.py:141: UserWarning: Data contains too many candlesticks to plot; downsampling to '8h'. See `Backtest.plot(resample=...)`
  warnings.warn(f"Data contains too many candlesticks to plot; downsampling to {freq!r}. "
c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning: no explicit representation of timezones available for np.datetime64
  return convert(array.astype("datetime64[us]"))

GridPlot(id='p1545', ...)

In [45]:
import pandas as pd
import datetime as dt
from ta.volatility import AverageTrueRange
from backtesting import Backtest, Strategy

global_range_to_consider = 0
global_tp_multiple = 0
global_stop_trade_hour = 0
global_close_range_hour = 0

class OpeningRangeBreakout(Strategy):
    # variables
    range_to_consider = 5
    close_range_hour = 8
    tp_multiple = 1.5
    stop_trade_hour = 18

    # fixed variables
    risk_percent = 0.01
    max_leverage = 4
    my_equity = 10000
    open_range_hour = close_range_hour - range_to_consider

    # def init(self, range_to_consider, tp_multiple, stop_trade_hour, close_range_hour):
    def init(self):
        self.current_day = None
        self.opening_range_high = None
        self.opening_range_low = None
        if global_range_to_consider != 0:
            self.range_to_consider = global_range_to_consider

        if global_tp_multiple != 0:
            self.tp_multiple = global_tp_multiple

        if global_stop_trade_hour != 0:
            self.stop_trade_hour = global_stop_trade_hour

        if global_close_range_hour != 0:
            self.close_range_hour = global_close_range_hour

        if global_close_range_hour != 0 and global_range_to_consider != 0:
            self.open_range_hour = global_close_range_hour - global_range_to_consider

    def reset_range(self, day):
        self.current_day = day
        self.current_day_position_taked = False
        self.opening_range_high = None
        self.opening_range_low = None

    def get_position_size(self, entry_price: float, stop_price : float) -> int:
        per_share_risk = abs(entry_price - stop_price)
        print(per_share_risk)
        if per_share_risk == 0:
            return 0

        share_by_risk = (self.risk_percent * self.equity) / entry_price

        share_by_leverage = (self.max_leverage * self.equity) / entry_price
        print(f"share_by_risk = {share_by_risk} & share_by_leverage = {share_by_leverage}")

        return int(min(share_by_risk, share_by_leverage))

    def next(self):
        t = self.data.index[-1]
        current_bar_date = self.data.index[-1].date()

        if (self.current_day != current_bar_date):
            self.reset_range(current_bar_date)
            # print(f"new date {current_bar_date}")

        if self.open_range_hour < t.time().hour and t.time().hour <= self.close_range_hour:
            if self.opening_range_high is not None:
                self.opening_range_high = max(self.opening_range_high, self.data.High[-1])
            else:
                self.opening_range_high = self.data.High[-1]

            if self.opening_range_low is not None:
                    self.opening_range_low = min(self.opening_range_low, self.data.Low[-1])
            else:
                self.opening_range_low = self.data.Low[-1]

            if t.time().hour < self.close_range_hour:
                return

        # if t.time().hour == self.close_range_hour:
            # print(f"opening rang high is {self.opening_range_high}")
            # print(f"opening rang low is {self.opening_range_low}")

        if t.time().hour > self.close_range_hour and self.opening_range_high is not None and self.opening_range_low is not None:
            c1 = self.data.Open[-1] < self.opening_range_high and self.data.Close[-1] > self.opening_range_high
            c2 = (self.opening_range_high - self.opening_range_low) < self.data['ATR'][-1] * 2.5
            c3 = (self.opening_range_high - self.opening_range_low) > self.data['ATR'][-1] * 1.0
            c4 = t.time().hour < self.stop_trade_hour

            if not self.current_day_position_taked:
                if c1 and c2 and c3 and c4:
                    planned_entry_price = self.data.Close[-1]
                    tp_price = self.opening_range_high + (planned_entry_price - self.opening_range_low) * self.tp_multiple
                    sl_price = self.opening_range_low
                    per_share_risk = abs(planned_entry_price - sl_price)
                    position_size = int((self.risk_percent * self.my_equity) / per_share_risk)

                    # print(f"per_share_risk = {per_share_risk} & risk_percent = {self.risk_percent} & equity = {self.my_equity}")
                    # print(f'Go long tp = {tp_price} sl = {sl_price} position size = {position_size}')
                    order = self.buy(size = position_size, tp=tp_price, sl=sl_price)
                    # print(f"c2 = {c2} & c3 = {c3}")
                    # print(order)
                    # print('--------------------------')
                    self.current_day_position_taked = True
                    # else:
                    #     print('conditions not met, do nothing')

        # if self.position:
        #     print(self.position)


def per_share_commission(size, price):
    return abs(size) * 0.0005

timezone = "Europe/London"

df = pd.read_csv("./Trading Data/GBPJPY_H1.csv",sep=',', parse_dates=['Date'], index_col='Date')
df.index = pd.to_datetime(df.index, utc=True).tz_convert(timezone)
df = df.loc['2020-01-01' : '2026-9-16']

indicator_atr = AverageTrueRange(df['High'], df['Low'], df['Close'], window=14)
df['ATR'] = indicator_atr._atr
result = []

range_to_consider_list = [3]
close_range_hour_list = [6,7,8,9]
stop_trade_hour_list = [18,19,20,21]
tp_multiple_list = [1,1.5,2,2.5,3,3.5,4,4.5,5,5.5,6]
for range in range_to_consider_list:
    for close_range_hour in close_range_hour_list:
        for stop_trade_hour in stop_trade_hour_list:
            for tp_multiple in tp_multiple_list:
                # range_to_consider, tp_multiple, stop_trade_hour, close_range_hour
                global_range_to_consider = range
                global_close_range_hour = close_range_hour
                global_stop_trade_hour = stop_trade_hour
                global_tp_multiple = tp_multiple


                bt = Backtest(df, OpeningRangeBreakout, margin=0.02, finalize_trades=True)
                stats = bt.run()

                result.append(f"range to consider = {range} & close range hour = {close_range_hour} & stop_trade_hour = {stop_trade_hour} & tp_multiple = {tp_multiple}")
                result.append(f"Return [%] = {stats['Return [%]']} | Return (Ann.) [%] = {stats['Return (Ann.) [%]']} | Max. Drawdown [%] = {stats['Max. Drawdown [%]']} | Win Rate [%] = {stats['Win Rate [%]']}")
                result.append("----------------------------------------------")

                print(f"range to consider = {range} & close range hour = {close_range_hour} & stop_trade_hour = {stop_trade_hour} & tp_multiple = {tp_multiple} DONE")



# Return [%] Return (Ann.) [%] Max. Drawdown [%]
result

range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 1 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 1.5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 2 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 2.5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 3 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 3.5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 4 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 4.5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 5.5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 6 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 1 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 1.5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 2 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 2.5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 3 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 3.5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 4 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 4.5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 5.5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 6 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 1 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 1.5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 2 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 2.5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 3 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 3.5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 4 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 4.5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 5.5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 6 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 1 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 1.5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 2 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 2.5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 3 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 3.5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 4 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 4.5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 5.5 DONE
range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 6 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 1 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 1.5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 2 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 2.5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 3 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 3.5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 4 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 4.5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 5.5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 6 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 1 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 1.5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 2 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 2.5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 3 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 3.5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 4 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 4.5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 5.5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 6 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 20 & tp_multiple = 1 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 20 & tp_multiple = 1.5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 20 & tp_multiple = 2 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 20 & tp_multiple = 2.5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 20 & tp_multiple = 3 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 20 & tp_multiple = 3.5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 20 & tp_multiple = 4 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 20 & tp_multiple = 4.5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 20 & tp_multiple = 5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 20 & tp_multiple = 5.5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 20 & tp_multiple = 6 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 21 & tp_multiple = 1 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 21 & tp_multiple = 1.5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 21 & tp_multiple = 2 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 21 & tp_multiple = 2.5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 21 & tp_multiple = 3 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 21 & tp_multiple = 3.5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 21 & tp_multiple = 4 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 21 & tp_multiple = 4.5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 21 & tp_multiple = 5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 21 & tp_multiple = 5.5 DONE
range to consider = 3 & close range hour = 7 & stop_trade_hour = 21 & tp_multiple = 6 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 18 & tp_multiple = 1 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 18 & tp_multiple = 1.5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 18 & tp_multiple = 2 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 18 & tp_multiple = 2.5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 18 & tp_multiple = 3 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 18 & tp_multiple = 3.5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 18 & tp_multiple = 4 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 18 & tp_multiple = 4.5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 18 & tp_multiple = 5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 18 & tp_multiple = 5.5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 18 & tp_multiple = 6 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 19 & tp_multiple = 1 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 19 & tp_multiple = 1.5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 19 & tp_multiple = 2 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 19 & tp_multiple = 2.5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 19 & tp_multiple = 3 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 19 & tp_multiple = 3.5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 19 & tp_multiple = 4 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 19 & tp_multiple = 4.5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 19 & tp_multiple = 5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 19 & tp_multiple = 5.5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 19 & tp_multiple = 6 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 20 & tp_multiple = 1 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 20 & tp_multiple = 1.5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 20 & tp_multiple = 2 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 20 & tp_multiple = 2.5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 20 & tp_multiple = 3 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 20 & tp_multiple = 3.5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 20 & tp_multiple = 4 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 20 & tp_multiple = 4.5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 20 & tp_multiple = 5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 20 & tp_multiple = 5.5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 20 & tp_multiple = 6 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 21 & tp_multiple = 1 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 21 & tp_multiple = 1.5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 21 & tp_multiple = 2 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 21 & tp_multiple = 2.5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 21 & tp_multiple = 3 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 21 & tp_multiple = 3.5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 21 & tp_multiple = 4 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 21 & tp_multiple = 4.5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 21 & tp_multiple = 5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 21 & tp_multiple = 5.5 DONE
range to consider = 3 & close range hour = 8 & stop_trade_hour = 21 & tp_multiple = 6 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 18 & tp_multiple = 1 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 18 & tp_multiple = 1.5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 18 & tp_multiple = 2 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 18 & tp_multiple = 2.5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 18 & tp_multiple = 3 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 18 & tp_multiple = 3.5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 18 & tp_multiple = 4 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 18 & tp_multiple = 4.5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 18 & tp_multiple = 5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 18 & tp_multiple = 5.5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 18 & tp_multiple = 6 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 19 & tp_multiple = 1 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 19 & tp_multiple = 1.5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 19 & tp_multiple = 2 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 19 & tp_multiple = 2.5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 19 & tp_multiple = 3 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 19 & tp_multiple = 3.5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 19 & tp_multiple = 4 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 19 & tp_multiple = 4.5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 19 & tp_multiple = 5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 19 & tp_multiple = 5.5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 19 & tp_multiple = 6 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 20 & tp_multiple = 1 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 20 & tp_multiple = 1.5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 20 & tp_multiple = 2 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 20 & tp_multiple = 2.5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 20 & tp_multiple = 3 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 20 & tp_multiple = 3.5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 20 & tp_multiple = 4 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 20 & tp_multiple = 4.5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 20 & tp_multiple = 5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 20 & tp_multiple = 5.5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 20 & tp_multiple = 6 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 21 & tp_multiple = 1 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 21 & tp_multiple = 1.5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 21 & tp_multiple = 2 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 21 & tp_multiple = 2.5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 21 & tp_multiple = 3 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 21 & tp_multiple = 3.5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 21 & tp_multiple = 4 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 21 & tp_multiple = 4.5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 21 & tp_multiple = 5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 21 & tp_multiple = 5.5 DONE
range to consider = 3 & close range hour = 9 & stop_trade_hour = 21 & tp_multiple = 6 DONE

['range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 1',
 'Return [%] = 29.432439999999517 | Return (Ann.) [%] = 3.1488550026936624 | Max. Drawdown [%] = -18.97069560280911 | Win Rate [%] = 59.078590785907856',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 1.5',
 'Return [%] = 75.56496999999915 | Return (Ann.) [%] = 6.997716086485983 | Max. Drawdown [%] = -13.228671498775846 | Win Rate [%] = 48.6449864498645',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 2',
 'Return [%] = 63.2978699999988 | Return (Ann.) [%] = 6.0704046316774285 | Max. Drawdown [%] = -13.113328559272952 | Win Rate [%] = 39.295392953929536',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 2.5',
 'Return [%] = 107.26078499999755 | Return (Ann.) [%] = 9.153180417271024 | Max. Drawdown [%] = -14.477292985624024 | Win Rate [%] = 35.09485094850949',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 3',
 'Return [%] = 132.3651699999976 | Return (Ann.) [%] = 10.663241101430355 | Max. Drawdown [%] = -16.089083297590612 | Win Rate [%] = 31.43631436314363',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 3.5',
 'Return [%] = 191.89680499999687 | Return (Ann.) [%] = 13.73847178079397 | Max. Drawdown [%] = -14.72125300353101 | Win Rate [%] = 29.67479674796748',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 4',
 'Return [%] = 205.75146999999677 | Return (Ann.) [%] = 14.374063619688648 | Max. Drawdown [%] = -17.933302629442828 | Win Rate [%] = 26.964769647696478',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 4.5',
 'Return [%] = 257.40827999999675 | Return (Ann.) [%] = 16.539920373560403 | Max. Drawdown [%] = -17.567500465608333 | Win Rate [%] = 25.745257452574528',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 5',
 'Return [%] = 294.46136999999544 | Return (Ann.) [%] = 17.92960823710372 | Max. Drawdown [%] = -18.641417417570427 | Win Rate [%] = 24.390243902439025',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 5.5',
 'Return [%] = 289.4415049999953 | Return (Ann.) [%] = 17.748241972009794 | Max. Drawdown [%] = -21.182651648256588 | Win Rate [%] = 22.35772357723577',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 18 & tp_multiple = 6',
 'Return [%] = 270.89086999999677 | Return (Ann.) [%] = 17.0596609196056 | Max. Drawdown [%] = -21.74356265970393 | Win Rate [%] = 20.32520325203252',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 1',
 'Return [%] = 29.24881999999947 | Return (Ann.) [%] = 3.1312589781005595 | Max. Drawdown [%] = -18.468185116690215 | Win Rate [%] = 59.06040268456376',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 1.5',
 'Return [%] = 75.028849999999 | Return (Ann.) [%] = 6.9583986766610595 | Max. Drawdown [%] = -12.178938086874979 | Win Rate [%] = 48.59060402684563',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 2',
 'Return [%] = 61.64947999999873 | Return (Ann.) [%] = 5.941160062060402 | Max. Drawdown [%] = -13.113328559272952 | Win Rate [%] = 39.19463087248322',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 2.5',
 'Return [%] = 103.27254499999756 | Return (Ann.) [%] = 8.898609905414334 | Max. Drawdown [%] = -15.16046623264372 | Win Rate [%] = 34.899328859060404',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 3',
 'Return [%] = 128.87434999999758 | Return (Ann.) [%] = 10.462123635099507 | Max. Drawdown [%] = -16.727394556141395 | Win Rate [%] = 31.2751677852349',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 3.5',
 'Return [%] = 188.903404999997 | Return (Ann.) [%] = 13.59766863030476 | Max. Drawdown [%] = -14.72125300353101 | Win Rate [%] = 29.53020134228188',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 4',
 'Return [%] = 203.25548999999685 | Return (Ann.) [%] = 14.261456187997767 | Max. Drawdown [%] = -17.933302629442828 | Win Rate [%] = 26.845637583892618',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 4.5',
 'Return [%] = 255.4097199999966 | Return (Ann.) [%] = 16.461414857142476 | Max. Drawdown [%] = -18.12157746426488 | Win Rate [%] = 25.63758389261745',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 5',
 'Return [%] = 292.9602299999953 | Return (Ann.) [%] = 17.875586335139925 | Max. Drawdown [%] = -19.169793271401613 | Win Rate [%] = 24.295302013422816',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 5.5',
 'Return [%] = 288.4377849999953 | Return (Ann.) [%] = 17.71173130164536 | Max. Drawdown [%] = -21.71006012751947 | Win Rate [%] = 22.28187919463087',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 19 & tp_multiple = 6',
 'Return [%] = 270.38456999999676 | Return (Ann.) [%] = 17.040446286085896 | Max. Drawdown [%] = -22.299004111850074 | Win Rate [%] = 20.268456375838927',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 1',
 'Return [%] = 27.483809999999743 | Return (Ann.) [%] = 2.9609895756348648 | Max. Drawdown [%] = -20.527949632927367 | Win Rate [%] = 59.01856763925729',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 1.5',
 'Return [%] = 75.76036499999933 | Return (Ann.) [%] = 7.012019498938615 | Max. Drawdown [%] = -13.71124946600083 | Win Rate [%] = 48.673740053050395',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 2',
 'Return [%] = 62.07384999999904 | Return (Ann.) [%] = 5.97454389299148 | Max. Drawdown [%] = -14.254543230747963 | Win Rate [%] = 39.257294429708224',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 2.5',
 'Return [%] = 105.69394999999786 | Return (Ann.) [%] = 9.053687218615991 | Max. Drawdown [%] = -15.540884530547638 | Win Rate [%] = 35.0132625994695',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 3',
 'Return [%] = 129.3722099999979 | Return (Ann.) [%] = 10.490971281707417 | Max. Drawdown [%] = -17.011456706027605 | Win Rate [%] = 31.29973474801061',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 3.5',
 'Return [%] = 186.73336999999722 | Return (Ann.) [%] = 13.494790027519144 | Max. Drawdown [%] = -14.656152735370377 | Win Rate [%] = 29.44297082228117',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 4',
 'Return [%] = 202.08379999999715 | Return (Ann.) [%] = 14.208313288175445 | Max. Drawdown [%] = -18.04666698533568 | Win Rate [%] = 26.790450928381965',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 4.5',
 'Return [%] = 255.2363749999971 | Return (Ann.) [%] = 16.454587393571217 | Max. Drawdown [%] = -17.685343072687875 | Win Rate [%] = 25.59681697612732',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 5',
 'Return [%] = 288.0157299999958 | Return (Ann.) [%] = 17.696354106814628 | Max. Drawdown [%] = -18.68023999543076 | Win Rate [%] = 24.137931034482758',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 5.5',
 'Return [%] = 283.992504999996 | Return (Ann.) [%] = 17.54902807867893 | Max. Drawdown [%] = -21.10151651681573 | Win Rate [%] = 22.148541114058357',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 20 & tp_multiple = 6',
 'Return [%] = 266.43850999999734 | Return (Ann.) [%] = 16.889891968532478 | Max. Drawdown [%] = -21.582592138703603 | Win Rate [%] = 20.159151193633953',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 1',
 'Return [%] = 33.498809999999665 | Return (Ann.) [%] = 3.5330071732423196 | Max. Drawdown [%] = -19.894710326310904 | Win Rate [%] = 59.39553219448095',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 1.5',
 'Return [%] = 78.10024499999919 | Return (Ann.) [%] = 7.182226536264524 | Max. Drawdown [%] = -13.725830183919651 | Win Rate [%] = 48.75164257555847',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 2',
 'Return [%] = 63.618529999999005 | Return (Ann.) [%] = 6.095413022251739 | Max. Drawdown [%] = -14.422154599083415 | Win Rate [%] = 39.2904073587385',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 2.5',
 'Return [%] = 108.7336899999978 | Return (Ann.) [%] = 9.24610749728414 | Max. Drawdown [%] = -16.32244659300497 | Win Rate [%] = 35.08541392904074',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 3',
 'Return [%] = 132.53092999999777 | Return (Ann.) [%] = 10.672724804626688 | Max. Drawdown [%] = -17.745795655628203 | Win Rate [%] = 31.40604467805519',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 3.5',
 'Return [%] = 190.88862999999714 | Return (Ann.) [%] = 13.691191844692142 | Max. Drawdown [%] = -14.75830293021052 | Win Rate [%] = 29.56636005256242',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 4',
 'Return [%] = 207.23559999999702 | Return (Ann.) [%] = 14.440638056594457 | Max. Drawdown [%] = -18.668533061566663 | Win Rate [%] = 26.938239159001316',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 4.5',
 'Return [%] = 261.384714999997 | Return (Ann.) [%] = 16.69497690325157 | Max. Drawdown [%] = -18.33103367792832 | Win Rate [%] = 25.75558475689882',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 5',
 'Return [%] = 295.1606099999957 | Return (Ann.) [%] = 17.95471023723769 | Max. Drawdown [%] = -19.300015307339347 | Win Rate [%] = 24.310118265440213',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 5.5',
 'Return [%] = 292.1339249999959 | Return (Ann.) [%] = 17.845772363045185 | Max. Drawdown [%] = -21.730962921273232 | Win Rate [%] = 22.339027595269382',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 6 & stop_trade_hour = 21 & tp_multiple = 6',
 'Return [%] = 275.5764699999973 | Return (Ann.) [%] = 17.23639777156194 | Max. Drawdown [%] = -22.245450395110012 | Win Rate [%] = 20.367936925098554',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 1',
 'Return [%] = 70.50517999999848 | Return (Ann.) [%] = 6.622360374398428 | Max. Drawdown [%] = -15.112544890691105 | Win Rate [%] = 61.12994350282486',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 1.5',
 'Return [%] = 103.1179999999984 | Return (Ann.) [%] = 8.888657089313256 | Max. Drawdown [%] = -14.337526285489677 | Win Rate [%] = 49.26553672316384',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 2',
 'Return [%] = 124.81263999999821 | Return (Ann.) [%] = 10.224689849622571 | Max. Drawdown [%] = -11.57327785322273 | Win Rate [%] = 41.24293785310734',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 2.5',
 'Return [%] = 176.90417499999901 | Return (Ann.) [%] = 13.020045253798829 | Max. Drawdown [%] = -11.669654607094026 | Win Rate [%] = 36.72316384180791',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 3',
 'Return [%] = 215.45968999999982 | Return (Ann.) [%] = 14.804502325778191 | Max. Drawdown [%] = -13.815896821462026 | Win Rate [%] = 33.10734463276836',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 3.5',
 'Return [%] = 250.93167500000084 | Return (Ann.) [%] = 16.284092724176414 | Max. Drawdown [%] = -14.980434251756748 | Win Rate [%] = 30.16949152542373',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 4',
 'Return [%] = 268.9123000000008 | Return (Ann.) [%] = 16.984440446129902 | Max. Drawdown [%] = -18.01735657038247 | Win Rate [%] = 27.45762711864407',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 4.5',
 'Return [%] = 298.99851499999966 | Return (Ann.) [%] = 18.091795165055878 | Max. Drawdown [%] = -19.54689234403242 | Win Rate [%] = 25.536723163841806',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 5',
 'Return [%] = 317.1615800000003 | Return (Ann.) [%] = 18.72522640801424 | Max. Drawdown [%] = -19.531791760902216 | Win Rate [%] = 23.728813559322035',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 5.5',
 'Return [%] = 351.8654500000004 | Return (Ann.) [%] = 19.870838778734523 | Max. Drawdown [%] = -22.98325405685756 | Win Rate [%] = 22.48587570621469',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 18 & tp_multiple = 6',
 'Return [%] = 348.4119399999993 | Return (Ann.) [%] = 19.760371929663624 | Max. Drawdown [%] = -20.495229293294017 | Win Rate [%] = 20.7909604519774',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 1',
 'Return [%] = 60.2992099999983 | Return (Ann.) [%] = 5.83442319213614 | Max. Drawdown [%] = -15.24711674780621 | Win Rate [%] = 60.467706013363035',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 1.5',
 'Return [%] = 91.54505499999861 | Return (Ann.) [%] = 8.12371817719133 | Max. Drawdown [%] = -14.447055333660696 | Win Rate [%] = 48.66369710467706',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 2',
 'Return [%] = 111.1559099999984 | Return (Ann.) [%] = 9.397680714681123 | Max. Drawdown [%] = -11.57327785322273 | Win Rate [%] = 40.645879732739424',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 2.5',
 'Return [%] = 163.24744499999906 | Return (Ann.) [%] = 12.33520063033251 | Max. Drawdown [%] = -11.72849574699394 | Win Rate [%] = 36.191536748329625',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 3',
 'Return [%] = 201.80295999999984 | Return (Ann.) [%] = 14.195548634378019 | Max. Drawdown [%] = -13.877518561543967 | Win Rate [%] = 32.62806236080178',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 3.5',
 'Return [%] = 237.27494500000117 | Return (Ann.) [%] = 15.73074015545779 | Max. Drawdown [%] = -14.980434251756748 | Win Rate [%] = 29.73273942093541',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 4',
 'Return [%] = 255.25557000000094 | Return (Ann.) [%] = 16.45534356293432 | Max. Drawdown [%] = -18.115742723980922 | Win Rate [%] = 27.060133630289535',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 4.5',
 'Return [%] = 285.3417849999998 | Return (Ann.) [%] = 17.598587944562304 | Max. Drawdown [%] = -19.645931498121037 | Win Rate [%] = 25.16703786191537',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 5',
 'Return [%] = 303.5048500000003 | Return (Ann.) [%] = 18.251282465697226 | Max. Drawdown [%] = -19.625095086702316 | Win Rate [%] = 23.385300668151448',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 5.5',
 'Return [%] = 338.2087200000003 | Return (Ann.) [%] = 19.429573583131088 | Max. Drawdown [%] = -23.088066522798524 | Win Rate [%] = 22.160356347438753',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 19 & tp_multiple = 6',
 'Return [%] = 334.755209999999 | Return (Ann.) [%] = 19.316071398691072 | Max. Drawdown [%] = -20.582929148437323 | Win Rate [%] = 20.489977728285076',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 20 & tp_multiple = 1',
 'Return [%] = 57.2828199999983 | Return (Ann.) [%] = 5.593094996622683 | Max. Drawdown [%] = -15.783944645630942 | Win Rate [%] = 60.35049288061336',
 '----------------------------------------------',
 'range to consider = 3 & close range hour = 7 & stop_trade_hour = 20 & tp_multiple = 1.5',
 'Return [%] = 90.07983499999857 | Return (Ann.) [%] = 8.023989285406286 | Max. Drawdown [%] = -15.029401975510392 | Win Rate [%] = 48.63088718510406',

In [85]:
import pandas as pd
import datetime as dt
from ta.volatility import AverageTrueRange
from backtesting import Backtest, Strategy

df = pd.read_csv("./Trading Data/GBPJPY_D1.csv",sep=',', parse_dates=['Date'], index_col='Date')

previous_row = None
is_long : int = 0
is_not_long : int = 0
is_short : int = 0
is_not_short : int = 0
in_side_bar : int = 0
for index, row in df.iterrows():
    if previous_row is None:
        previous_row = row
    else:
        # print(index.date())
        # if index.date() == dt.datetime(2010,9,6).date():
        #     print(index.date())

        c_long = previous_row.Open < previous_row.Close and row['High'] > previous_row.High 
        c_not_long = previous_row.Open < previous_row.Close and row['Low'] < previous_row.Low 
        c_short = previous_row.Open > previous_row.Close and row['Low'] < previous_row.Low 
        c_not_short = previous_row.Open > previous_row.Close and row['High'] > previous_row.High 
        previous_row = row

        if c_long:
            is_long += 1
            continue
        if c_not_long:
            is_not_long += 1
            continue
        if c_short:
            is_short += 1
            continue
        if c_not_short:
            is_not_short += 1
            continue

        in_side_bar += 1

print(is_long)
print(is_not_long)
print(is_short)
print(is_not_short)
print(in_side_bar)
# print(df.count())
# df

1836
430
1328
401
1020

In [182]:
import pandas as pd

timezone = "Europe/London"

start_date = '2020-01-1'
end_date = '2026-09-16'

df_d1 = pd.read_csv("./Trading Data/GBPJPY_D1.csv",sep=',', parse_dates=['Date'], index_col='Date')
df_d1 = df_d1.loc[start_date : end_date]

df_h1 = pd.read_csv("./Trading Data/GBPJPY_H1.csv",sep=',', parse_dates=['Date'], index_col='Date')
df_h1 = df_h1.loc[start_date : end_date]

previous_row = None
d1_tf_direction_list = []

for index, row in df_d1.iterrows():
    df_by_day = df_h1.loc[f'{index.date()}' : f'{index.date()}']

    if index.weekday() == 5 or index.weekday() == 6:
        for index2, row2 in df_by_day.iterrows():
            d1_tf_direction_list.append(0)
        continue

    if previous_row is None:
        previous_row = row
    else:
        # print(previous_row)
        c_long = previous_row.Open < previous_row.Close 
        c_short = previous_row.Open > previous_row.Close

        previous_row = row

        if c_long:
            # print(f"long {index}")
            for index2, row2 in df_by_day.iterrows():
                d1_tf_direction_list.append(1)
            continue
        if c_short:
            # print(f"short {index}")
            for index2, row2 in df_by_day.iterrows():
                d1_tf_direction_list.append(2)
            continue

    for index2, row2 in df_by_day.iterrows():
        d1_tf_direction_list.append(0)
    

    
df_h1['dl_direction'] = d1_tf_direction_list
df_h1.index = pd.to_datetime(df_h1.index, utc=True).tz_convert(timezone)

print(df_h1)

                              Open     High      Low    Close  Tickvol  \
Date
2020-01-01 22:00:00+00:00  144.044  144.077  143.732  143.959     5101
2020-01-01 23:00:00+00:00  143.957  144.086  143.921  144.053     2728
2020-01-02 00:00:00+00:00  144.053  144.180  144.004  144.101     5428
2020-01-02 01:00:00+00:00  144.099  144.186  144.003  144.056     5343
2020-01-02 02:00:00+00:00  144.050  144.065  143.912  143.979     4232
...                            ...      ...      ...      ...      ...
2026-09-16 20:00:00+01:00  208.640  209.055  208.579  209.055    28303
2026-09-16 21:00:00+01:00  209.054  209.248  209.003  209.033     7839
2026-09-16 22:00:00+01:00  208.863  209.071  208.863  208.975     1106
2026-09-16 23:00:00+01:00  208.975  209.096  208.974  209.061     4885
2026-09-17 00:00:00+01:00  209.062  209.090  208.788  208.807     9886

                           dl_direction
Date
2020-01-01 22:00:00+00:00             0
2020-01-01 23:00:00+00:00             0
2020-01-02 00:00:00+00:00             1
2020-01-02 01:00:00+00:00             1
2020-01-02 02:00:00+00:00             1
...                                 ...
2026-09-16 20:00:00+01:00             1
2026-09-16 21:00:00+01:00             1
2026-09-16 22:00:00+01:00             1
2026-09-16 23:00:00+01:00             1
2026-09-17 00:00:00+01:00             1

[41847 rows x 6 columns]

In [7]:
import pandas as pd
import datetime as dt
from ta.volatility import AverageTrueRange
from backtesting import Backtest, Strategy

class OpeningRangeBreakout(Strategy):
    # variables
    range_to_consider = 3
    tp_multiple = 5.5
    stop_trade_hour = 18
    close_range_hour = 8

    # fixed variables
    my_equity = 10000
    max_leverage = 4
    risk_percent = 0.01
    open_range_hour = close_range_hour - range_to_consider

    def init(self):
        self.current_day = None
        self.opening_range_high = None
        self.opening_range_low = None

    def reset_range(self, day):
        self.current_day = day
        self.current_day_position_taked = False
        self.opening_range_high = None
        self.opening_range_low = None

    def get_position_size(self, entry_price: float, stop_price : float) -> int:
        per_share_risk = abs(entry_price - stop_price)
        print(per_share_risk)
        if per_share_risk == 0:
            return 0

        share_by_risk = (self.risk_percent * self.equity) / entry_price

        share_by_leverage = (self.max_leverage * self.equity) / entry_price
        print(f"share_by_risk = {share_by_risk} & share_by_leverage = {share_by_leverage}")

        return int(min(share_by_risk, share_by_leverage))

    def next(self):
        t = self.data.index[-1]
        current_bar_date = self.data.index[-1].date()
        # print(self.data['dl_direction'][-1])
        # print(self.data['ATR'][-1])

        if (self.current_day != current_bar_date):
            self.reset_range(current_bar_date)
            # print(f"new date {current_bar_date}")

        if self.open_range_hour < t.time().hour and t.time().hour <= self.close_range_hour:
            if self.opening_range_high is not None:
                self.opening_range_high = max(self.opening_range_high, self.data.High[-1])
            else:
                self.opening_range_high = self.data.High[-1]

            if self.opening_range_low is not None:
                    self.opening_range_low = min(self.opening_range_low, self.data.Low[-1])
            else:
                self.opening_range_low = self.data.Low[-1]

            if t.time().hour < self.close_range_hour:
                return

        if t.time().hour > self.close_range_hour and self.opening_range_high is not None and self.opening_range_low is not None:
            c_long = self.data.Open[-1] < self.opening_range_high and self.data.Close[-1] > self.opening_range_high and self.data['dl_direction'][-1] == 1
            c_short = self.data.Open[-1] > self.opening_range_low and self.data.Close[-1] < self.opening_range_low and self.data['dl_direction'][-1] == 2
            
            c2 = (self.opening_range_high - self.opening_range_low) < self.data['ATR'][-1] * 2.5
            c3 = (self.opening_range_high - self.opening_range_low) > self.data['ATR'][-1] * 1.0
            c4 = t.time().hour < self.stop_trade_hour

            if not self.current_day_position_taked:
                if c_long and c2 and c3 and c4:
                    planned_entry_price = self.data.Close[-1]
                    tp_price = self.opening_range_high + (planned_entry_price - self.opening_range_low) * self.tp_multiple
                    sl_price = self.opening_range_low
                    per_share_risk = abs(planned_entry_price - sl_price)
                    position_size = int((self.risk_percent * self.my_equity) / per_share_risk)

                    # print(f'Go long tp = {tp_price} sl = {sl_price} position size = {position_size}')
                    order = self.buy(size = position_size, tp=tp_price, sl=sl_price)
                    self.current_day_position_taked = True

                if c_short and c2 and c3 and c4:
                    planned_entry_price = self.data.Close[-1]
                    sl_price = self.opening_range_high
                    per_share_risk = abs(planned_entry_price - sl_price)
                    tp_price = self.opening_range_low - per_share_risk * self.tp_multiple
                    position_size = int((self.risk_percent * self.my_equity) / per_share_risk)

                    # print(f'Go short tp = {tp_price} sl = {sl_price} position size = {position_size}')
                    order = self.sell(size = position_size, tp=tp_price, sl=sl_price)
                    self.current_day_position_taked = True



timezone = "Europe/London"

start_date = '2020-01-1'
end_date = '2026-9-15'

df_d1 = pd.read_csv("./Trading Data/GBPJPY_D1.csv",sep=',', parse_dates=['Date'], index_col='Date')
df_d1 = df_d1.loc[start_date : end_date]

df_h1 = pd.read_csv("./Trading Data/GBPJPY_H1.csv",sep=',', parse_dates=['Date'], index_col='Date')
df_h1 = df_h1.loc[start_date : end_date]

previous_row = None
d1_tf_direction_list = []

for index, row in df_d1.iterrows():
    df_by_day = df_h1.loc[f'{index.date()}' : f'{index.date()}']

    if index.weekday() == 5 or index.weekday() == 6:
        for index2, row2 in df_by_day.iterrows():
            d1_tf_direction_list.append(0)
        continue

    if previous_row is None:
        previous_row = row
    else:
        # print(previous_row)
        c_long = previous_row.Open < previous_row.Close 
        c_short = previous_row.Open > previous_row.Close

        previous_row = row

        if c_long:
            # print(f"long {index}")
            for index2, row2 in df_by_day.iterrows():
                d1_tf_direction_list.append(1)
            continue
        if c_short:
            # print(f"short {index}")
            for index2, row2 in df_by_day.iterrows():
                d1_tf_direction_list.append(2)
            continue

    for index2, row2 in df_by_day.iterrows():
        d1_tf_direction_list.append(0)
    

    
df_h1['dl_direction'] = d1_tf_direction_list
df_h1.index = pd.to_datetime(df_h1.index, utc=True).tz_convert(timezone)

indicator_atr = AverageTrueRange(df_h1['High'], df_h1['Low'], df_h1['Close'], window=14)
df_h1['ATR'] = indicator_atr._atr

bt = Backtest(df_h1, OpeningRangeBreakout, margin=0.02, finalize_trades=True)

stats = bt.run()

print(stats)

bt.plot()

Start                     2020-01-01 22:00...
End                       2026-09-16 00:00...
Duration                   2449 days 01:00:00
Exposure Time [%]                     61.4064
Equity Final [$]                    19412.633
Equity Peak [$]                    23534.5565
Return [%]                           94.12633
Buy & Hold Return [%]                45.29762
Return (Ann.) [%]                     8.29779
Volatility (Ann.) [%]                16.38623
CAGR [%]                             10.39894
Sharpe Ratio                          0.50639
Sortino Ratio                         0.96215
Calmar Ratio                          0.30353
Alpha [%]                            91.95781
Beta                                  0.04787
Max. Drawdown [%]                   -27.33744
Avg. Drawdown [%]                     -1.5468
Max. Drawdown Duration      718 days 18:00:00
Avg. Drawdown Duration       15 days 11:00:00
# Trades                                  759
Win Rate [%]                         26.08696
Best Trade [%]                         5.8409
Worst Trade [%]                      -1.46273
Avg. Trade [%]                        0.05701
Max. Trade Duration          21 days 00:00:00
Avg. Trade Duration           3 days 07:00:00
Profit Factor                         1.23063
Expectancy [%]                        0.06078
SQN                                   1.68962
Kelly Criterion                       0.04257
_strategy                 OpeningRangeBrea...
_equity_curve                             ...
_trades                        Size  Entry...
dtype: object

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\_plotting.py:141: UserWarning: Data contains too many candlesticks to plot; downsampling to '8h'. See `Backtest.plot(resample=...)`
  warnings.warn(f"Data contains too many candlesticks to plot; downsampling to {freq!r}. "
c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\bokeh\util\serialization.py:256: UserWarning: no explicit representation of timezones available for np.datetime64
  return convert(array.astype("datetime64[us]"))

GridPlot(id='p2965', ...)