In [2]:
from ta.volatility import AverageTrueRange

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

from backtesting import Strategy
from backtesting import Backtest, set_bokeh_output
set_bokeh_output(notebook=False)

from datetime import timedelta

import sys
sys.path.append('../utils')
import Util
import importlib
importlib.reload(Util)

from enum import Enum
import time

from random import randint
import random

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\_plotting.py:55: UserWarning: Jupyter Notebook detected. Setting Bokeh output to notebook. This may not work in Jupyter clients without JavaScript support, such as old IDEs. Reset with `backtesting.set_bokeh_output(notebook=False)`.
  warnings.warn('Jupyter Notebook detected. '

In [3]:
pair = 'GBPJPY'

df_d1_raw = pd.read_csv(f"../Trading Data/{pair}_D1.csv",sep=',', parse_dates=['Date'], index_col='Date')
df_h4_raw = pd.read_csv(f"../Trading Data/{pair}_H4.csv",sep=',', parse_dates=['Date'], index_col='Date')
df_m15_raw = pd.read_csv(f"../Trading Data/{pair}_M15.csv",sep=',', parse_dates=['Date'], index_col='Date')

print(df_d1_raw)
print(df_h4_raw)
print(df_m15_raw)

               Open     High      Low    Close  Tickvol
Date
2010-09-10  129.605  130.065  128.995  129.255   172229
2010-09-13  129.565  130.115  128.780  129.090   215859
2010-09-14  129.105  129.430  127.640  129.015   226170
2010-09-15  129.015  134.070  128.555  133.975   252317
2010-09-16  133.975  134.260  132.970  134.150   222443
...             ...      ...      ...      ...      ...
2026-09-18  208.323  211.276  208.233  210.095   364707
2026-09-21  210.296  210.762  209.676  210.321   243731
2026-09-22  210.321  210.892  209.513  210.080   333200
2026-09-23  210.080  210.176  209.422  209.564   273936
2026-09-24  209.566  210.105  208.768  209.848   199988

[4183 rows x 5 columns]
                        Open     High      Low    Close  Tickvol
Date
2010-09-10 04:00:00  129.605  129.630  128.995  129.385    25539
2010-09-10 08:00:00  129.380  129.985  129.275  129.785    44503
2010-09-10 12:00:00  129.785  130.065  129.425  129.570    54127
2010-09-10 16:00:00  129.580  129.770  129.120  129.135    39740
2010-09-10 20:00:00  129.130  129.335  129.120  129.255     8320
...                      ...      ...      ...      ...      ...
2026-09-23 20:00:00  209.580  209.701  209.431  209.564    16661
2026-09-24 00:00:00  209.566  209.638  208.768  209.072    51880
2026-09-24 04:00:00  209.072  209.859  209.019  209.838    38121
2026-09-24 08:00:00  209.840  210.067  209.417  209.996    62442
2026-09-24 12:00:00  209.997  210.105  209.846  209.848    47545

[25029 rows x 5 columns]
                        Open     High      Low    Close  Tickvol
Date
2020-08-19 16:15:00  139.383  139.441  139.350  139.420    13401
2020-08-19 16:30:00  139.420  139.504  139.397  139.493     2033
2020-08-19 16:45:00  139.495  139.495  139.427  139.441     1798
2020-08-19 17:00:00  139.441  139.441  139.324  139.329     2242
2020-08-19 17:15:00  139.331  139.352  139.272  139.272     2696
...                      ...      ...      ...      ...      ...
2026-09-24 18:45:00  209.996  210.001  209.932  209.961     2550
2026-09-24 19:00:00  209.961  209.998  209.888  209.938     4040
2026-09-24 19:15:00  209.939  209.960  209.918  209.954     3388
2026-09-24 19:30:00  209.953  209.959  209.902  209.931     3296
2026-09-24 19:45:00  209.932  209.954  209.914  209.945     3174

[150000 rows x 5 columns]

In [4]:
structure_d1_window = 2
structure_m15_window = 2

date_format = '%Y-%m-%d %H:%M'
# start_date = '2023-1-1 00:00'
# end_date = '2024-3-29 00:00'
start_date = datetime.strptime('2021-1-1 00:00', date_format)
end_date = datetime.strptime('2026-9-16 00:00', date_format)
# start_date = '2022-01-1 00:00'

timezone = "Europe/London"

# nombre de jours pour les high.low
define_key_level_window = 90

gap_look_ahead = 6

# nombre de candle au dessus/ en desous de key level après breakout
breakout_candles = 9

# nombre de jours à chercher key level
key_level_lookback_candle = 100

# vérifier si 30 candle dans ke passé pour valider un valid breakout,
# un valid breakout doit avoir {breakout_candles} candles au dessus du resistant level
breakout_candles_lookback = 30

start_trade_hour = 9
stop_trade_hour = 19

atr_multiplier = 0.7
min_touched = 3

In [5]:
# process D1 data
df_d1 = df_d1_raw.loc[start_date - timedelta(days=30) : end_date]

df_d1 = Util.implement_market_structure_states_fixed_pivots(df_d1, n=structure_d1_window)
df_d1["state_changed"] = df_d1["market_state"] != df_d1[
    "market_state"
].shift(1)
for state in df_d1[df_d1["state_changed"]][["Close", "market_state"]].iterrows():
    print(state)
df_d1 = df_d1.loc[start_date : end_date]

(Timestamp('2020-12-02 00:00:00'), Close           139.632
market_state        NaN
Name: 2020-12-02 00:00:00, dtype: object)
(Timestamp('2020-12-03 00:00:00'), Close           139.68
market_state       NaN
Name: 2020-12-03 00:00:00, dtype: object)
(Timestamp('2020-12-04 00:00:00'), Close           139.937
market_state        NaN
Name: 2020-12-04 00:00:00, dtype: object)
(Timestamp('2020-12-07 00:00:00'), Close           139.114
market_state        NaN
Name: 2020-12-07 00:00:00, dtype: object)
(Timestamp('2020-12-08 00:00:00'), Close           139.134
market_state        NaN
Name: 2020-12-08 00:00:00, dtype: object)
(Timestamp('2020-12-09 00:00:00'), Close           139.302
market_state        NaN
Name: 2020-12-09 00:00:00, dtype: object)
(Timestamp('2020-12-10 00:00:00'), Close           138.634
market_state        NaN
Name: 2020-12-10 00:00:00, dtype: object)
(Timestamp('2020-12-11 00:00:00'), Close           137.506
market_state    BEARISH
Name: 2020-12-11 00:00:00, dtype: object)
(Timestamp('2020-12-24 00:00:00'), Close           140.684
market_state    BULLISH
Name: 2020-12-24 00:00:00, dtype: object)
(Timestamp('2021-03-23 00:00:00'), Close           149.321
market_state    BEARISH
Name: 2021-03-23 00:00:00, dtype: object)
(Timestamp('2021-03-31 00:00:00'), Close           152.669
market_state    BULLISH
Name: 2021-03-31 00:00:00, dtype: object)
(Timestamp('2021-04-22 00:00:00'), Close           149.486
market_state    BEARISH
Name: 2021-04-22 00:00:00, dtype: object)
(Timestamp('2021-05-10 00:00:00'), Close           153.726
market_state    BULLISH
Name: 2021-05-10 00:00:00, dtype: object)
(Timestamp('2021-06-09 00:00:00'), Close           154.703
market_state    BEARISH
Name: 2021-06-09 00:00:00, dtype: object)
(Timestamp('2021-09-02 00:00:00'), Close           152.142
market_state    BULLISH
Name: 2021-09-02 00:00:00, dtype: object)
(Timestamp('2021-09-16 00:00:00'), Close           151.398
market_state    BEARISH
Name: 2021-09-16 00:00:00, dtype: object)
(Timestamp('2021-09-27 00:00:00'), Close           152.056
market_state    BULLISH
Name: 2021-09-27 00:00:00, dtype: object)
(Timestamp('2021-11-01 00:00:00'), Close           155.776
market_state    BEARISH
Name: 2021-11-01 00:00:00, dtype: object)
(Timestamp('2021-11-16 00:00:00'), Close           154.166
market_state    BULLISH
Name: 2021-11-16 00:00:00, dtype: object)
(Timestamp('2021-11-26 00:00:00'), Close           150.781
market_state    BEARISH
Name: 2021-11-26 00:00:00, dtype: object)
(Timestamp('2021-12-15 00:00:00'), Close           151.204
market_state    BULLISH
Name: 2021-12-15 00:00:00, dtype: object)
(Timestamp('2022-01-18 00:00:00'), Close           155.827
market_state    BEARISH
Name: 2022-01-18 00:00:00, dtype: object)
(Timestamp('2022-02-10 00:00:00'), Close           157.341
market_state    BULLISH
Name: 2022-02-10 00:00:00, dtype: object)
(Timestamp('2022-02-24 00:00:00'), Close           154.481
market_state    BEARISH
Name: 2022-02-24 00:00:00, dtype: object)
(Timestamp('2022-03-16 00:00:00'), Close           156.048
market_state    BULLISH
Name: 2022-03-16 00:00:00, dtype: object)
(Timestamp('2022-05-11 00:00:00'), Close           159.087
market_state    BEARISH
Name: 2022-05-11 00:00:00, dtype: object)
(Timestamp('2022-05-30 00:00:00'), Close           161.394
market_state    BULLISH
Name: 2022-05-30 00:00:00, dtype: object)
(Timestamp('2022-07-01 00:00:00'), Close           163.526
market_state    BEARISH
Name: 2022-07-01 00:00:00, dtype: object)
(Timestamp('2022-07-18 00:00:00'), Close           165.186
market_state    BULLISH
Name: 2022-07-18 00:00:00, dtype: object)
(Timestamp('2022-07-29 00:00:00'), Close           162.226
market_state    BEARISH
Name: 2022-07-29 00:00:00, dtype: object)
(Timestamp('2022-09-06 00:00:00'), Close           164.999
market_state    BULLISH
Name: 2022-09-06 00:00:00, dtype: object)
(Timestamp('2022-09-21 00:00:00'), Close           162.648
market_state    BEARISH
Name: 2022-09-21 00:00:00, dtype: object)
(Timestamp('2022-10-13 00:00:00'), Close           166.814
market_state    BULLISH
Name: 2022-10-13 00:00:00, dtype: object)
(Timestamp('2022-11-11 00:00:00'), Close           164.176
market_state    BEARISH
Name: 2022-11-11 00:00:00, dtype: object)
(Timestamp('2022-12-09 00:00:00'), Close           167.508
market_state    BULLISH
Name: 2022-12-09 00:00:00, dtype: object)
(Timestamp('2022-12-20 00:00:00'), Close           160.482
market_state    BEARISH
Name: 2022-12-20 00:00:00, dtype: object)
(Timestamp('2023-01-09 00:00:00'), Close           160.624
market_state    BULLISH
Name: 2023-01-09 00:00:00, dtype: object)
(Timestamp('2023-02-01 00:00:00'), Close           159.495
market_state    BEARISH
Name: 2023-02-01 00:00:00, dtype: object)
(Timestamp('2023-02-13 00:00:00'), Close           160.595
market_state    BULLISH
Name: 2023-02-13 00:00:00, dtype: object)
(Timestamp('2023-03-15 00:00:00'), Close           160.736
market_state    BEARISH
Name: 2023-03-15 00:00:00, dtype: object)
(Timestamp('2023-03-29 00:00:00'), Close           163.358
market_state    BULLISH
Name: 2023-03-29 00:00:00, dtype: object)
(Timestamp('2023-07-12 00:00:00'), Close           179.752
market_state    BEARISH
Name: 2023-07-12 00:00:00, dtype: object)
(Timestamp('2023-07-31 00:00:00'), Close           182.606
market_state    BULLISH
Name: 2023-07-31 00:00:00, dtype: object)
(Timestamp('2023-08-23 00:00:00'), Close           184.145
market_state    BEARISH
Name: 2023-08-23 00:00:00, dtype: object)
(Timestamp('2023-10-11 00:00:00'), Close           183.455
market_state    BULLISH
Name: 2023-10-11 00:00:00, dtype: object)
(Timestamp('2023-12-07 00:00:00'), Close           181.596
market_state    BEARISH
Name: 2023-12-07 00:00:00, dtype: object)
(Timestamp('2024-01-04 00:00:00'), Close           183.382
market_state    BULLISH
Name: 2024-01-04 00:00:00, dtype: object)
(Timestamp('2024-01-31 00:00:00'), Close           186.296
market_state    BEARISH
Name: 2024-01-31 00:00:00, dtype: object)
(Timestamp('2024-02-08 00:00:00'), Close           188.338
market_state    BULLISH
Name: 2024-02-08 00:00:00, dtype: object)
(Timestamp('2024-03-11 00:00:00'), Close            188.26
market_state    BEARISH
Name: 2024-03-11 00:00:00, dtype: object)
(Timestamp('2024-03-19 00:00:00'), Close           191.869
market_state    BULLISH
Name: 2024-03-19 00:00:00, dtype: object)
(Timestamp('2024-04-01 00:00:00'), Close           190.228
market_state    BEARISH
Name: 2024-04-01 00:00:00, dtype: object)
(Timestamp('2024-04-09 00:00:00'), Close           192.348
market_state    BULLISH
Name: 2024-04-09 00:00:00, dtype: object)
(Timestamp('2024-06-04 00:00:00'), Close           197.755
market_state    BEARISH
Name: 2024-06-04 00:00:00, dtype: object)
(Timestamp('2024-06-19 00:00:00'), Close           200.965
market_state    BULLISH
Name: 2024-06-19 00:00:00, dtype: object)
(Timestamp('2024-07-17 00:00:00'), Close           203.136
market_state    BEARISH
Name: 2024-07-17 00:00:00, dtype: object)
(Timestamp('2024-09-02 00:00:00'), Close           193.077
market_state    BULLISH
Name: 2024-09-02 00:00:00, dtype: object)
(Timestamp('2024-09-04 00:00:00'), Close           188.797
market_state    BEARISH
Name: 2024-09-04 00:00:00, dtype: object)
(Timestamp('2024-09-26 00:00:00'), Close           194.299
market_state    BULLISH
Name: 2024-09-26 00:00:00, dtype: object)
(Timestamp('2024-11-15 00:00:00'), Close           194.764
market_state    BEARISH
Name: 2024-11-15 00:00:00, dtype: object)
(Timestamp('2024-12-27 00:00:00'), Close           198.448
market_state    BULLISH
Name: 2024-12-27 00:00:00, dtype: object)
(Timestamp('2025-01-10 00:00:00'), Close           192.503
market_state    BEARISH
Name: 2025-01-10 00:00:00, dtype: object)
(Timestamp('2025-03-17 00:00:00'), Close           193.928
market_state    BULLISH
Name: 2025-03-17 00:00:00, dtype: object)
(Timestamp('2025-04-03 00:00:00'), Close           190.836
market_state    BEARISH
Name: 2025-04-03 00:00:00, dtype: object)
(Timestamp('2025-04-23 00:00:00'), Close            189.86
market_state    BULLISH
Name: 2025-04-23 00:00:00, dtype: object)
(Timestamp('2025-07-30 00:00:00'), Close           197.886
market_state    BEARISH
Name: 2025-07-30 00:00:00, dtype: object)
(Timestamp('2025-08-12 00:00:00'), Close           199.518
market_state    BULLISH
Name: 2025-08-12 00:00:00, dtype: object)
(Timestamp('2025-08-20 00:00:00'), Close           198.226
market_state    BEARISH
Name: 2025-08-20 00:00:00, dtype: object)
(Timestamp('2025-09-08 00:00:00'), Close           199.723
market_state    BULLISH
Name: 2025-09-08 00:00:00, dtype: object)
(Timestamp('2025-09-30 00:00:00'), Close           198.839
market_state    BEARISH
Name: 2025-09-30 00:00:00, dtype: object)
(Timestamp('2025-10-06 00:00:00'), Close           202.654
market_state    BULLISH
Name: 2025-10-06 00:00:00, dtype: object)
(Timestamp('2025-11-04 00:00:00'), Close           200.155
market_state    BEARISH
Name: 2025-11-04 00:00:00, dtype: object)
(Timestamp('2025-11-18 00:00:00'), Close           204.438
market_state    BULLISH
Name: 2025-11-18 00:00:00, dtype: object)
(Timestamp('2026-02-10 00:00:00'), Close           210.561
market_state    BEARISH
Name: 2026-02-10 00:00:00, dtype: object)
(Timestamp('2026-02-24 00:00:00'), Close           210.224
market_state    BULLISH
Name: 2026-02-24 00:00:00, dtype: object)
(Timestamp('2026-03-30 00:00:00'), Close           210.598
market_state    BEARISH
Name: 2026-03-30 00:00:00, dtype: object)
(Timestamp('2026-04-09 00:00:00'), Close           213.599
market_state    BULLISH
Name: 2026-04-09 00:00:00, dtype: object)
(Timestamp('2026-04-30 00:00:00'), Close           213.107
market_state    BEARISH
Name: 2026-04-30 00:00:00, dtype: object)
(Timestamp('2026-05-25 00:00:00'), Close           214.592
market_state    BULLISH
Name: 2026-05-25 00:00:00, dtype: object)
(Timestamp('2026-06-18 00:00:00'), Close           212.961
market_state    BEARISH
Name: 2026-06-18 00:00:00, dtype: object)
(Timestamp('2026-06-29 00:00:00'), Close           214.706
market_state    BULLISH
Name: 2026-06-29 00:00:00, dtype: object)
(Timestamp('2026-07-30 00:00:00'), Close           215.005
market_state    BEARISH
Name: 2026-07-30 00:00:00, dtype: object)

In [6]:
# process h4 data
df_h4 = df_h4_raw.loc[start_date - timedelta(days=20) : end_date]
df_h4 = Util.implement_market_structure_states_fixed_pivots(df_h4, 5)
df_h4 = df_h4.loc[start_date : end_date]

h4_d1_direction_list = []
for i in range(len(df_d1)):
    row = df_d1.iloc[i]
    start_date_daily = row.name
    end_date_daily = start_date_daily + timedelta(hours=23, minutes=59)
    df_by_day = df_h4.loc[f'{start_date_daily}' : f'{end_date_daily}']

    for index2, row2 in df_by_day.iterrows():
        h4_d1_direction_list.append(df_d1.iloc[i-1]['market_state'])

df_h4['market_state_d1'] = h4_d1_direction_list

indicator_atr_14 = AverageTrueRange(df_h4['High'], df_h4['Low'], df_h4['Close'], window=14)
df_h4['ATR'] = indicator_atr_14._atr

df_h4

,Open,High,Low,Close,Tickvol,is_swing_high,is_swing_low,market_state,market_state_d1,ATR
Date,,,,,,,,,,
2021-01-04 00:00:00,140.944,141.304,140.776,141.005,37352,True,False,BULLISH,BEARISH,0.000000
2021-01-04 04:00:00,141.007,141.043,140.847,140.938,20550,False,False,BULLISH,BEARISH,0.000000
2021-01-04 08:00:00,140.936,141.064,140.412,140.757,47343,False,False,BULLISH,BEARISH,0.000000
2021-01-04 12:00:00,140.758,140.861,140.188,140.226,55445,False,False,BULLISH,BEARISH,0.000000
2021-01-04 16:00:00,140.227,140.233,139.687,139.870,55631,False,False,BULLISH,BEARISH,0.000000
...,...,...,...,...,...,...,...,...,...,...
2026-09-15 08:00:00,208.652,209.090,208.514,208.655,56407,False,False,BEARISH,BEARISH,0.567701
2026-09-15 12:00:00,208.655,209.211,208.607,209.168,74480,False,False,BULLISH,BEARISH,0.570294
2026-09-15 16:00:00,209.167,209.224,208.885,209.066,38410,False,False,BULLISH,BEARISH,0.553773
2026-09-15 20:00:00,209.064,209.082,208.872,209.019,18776,False,False,BULLISH,BEARISH,0.529218
2026-09-16 00:00:00,209.018,209.394,208.982,209.259,52853,False,False,BULLISH,BEARISH,0.520845

In [7]:
# process m15 data
df_m15 = df_m15_raw.loc[start_date - timedelta(hours=3): end_date]
df_m15 = Util.implement_market_structure_states_fixed_pivots(df_m15, n=structure_m15_window)

m15_daily_direction_list = []

index_list = []

df_m15 = df_m15.loc[start_date : end_date]
for i in range(len(df_h4)):
    row = df_h4.iloc[i]
    start_date_h4 = row.name
    end_date_h4 = start_date_h4 + timedelta(hours=3, minutes=59)
    df_by_day = df_m15.loc[f'{start_date_h4}' : f'{end_date_h4}']

    for index2, row2 in df_by_day.iterrows():
        # affect current market states of H4 candle because the result is market state of previous D1 candle
        m15_daily_direction_list.append(df_h4.iloc[i]['market_state_d1'])

        # ajust to daylight saving time
        dst = pd.Timestamp(index2, tz=timezone).dst()
        if dst == timedelta(0):
            index2 = index2 - timedelta(hours=1)
            index_list.append(index2)
        else:
            index_list.append(index2)

df_m15['market_state_d1'] = m15_daily_direction_list

df_m15.index = index_list

df_m15

,Open,High,Low,Close,Tickvol,is_swing_high,is_swing_low,market_state,market_state_d1
2021-01-03 23:00:00,140.944,141.110,140.944,141.100,2767,False,True,NaN,BEARISH
2021-01-03 23:15:00,141.099,141.204,141.070,141.186,1223,False,False,NaN,BEARISH
2021-01-03 23:30:00,141.186,141.304,141.158,141.282,1042,True,False,NaN,BEARISH
2021-01-03 23:45:00,141.278,141.301,141.218,141.244,1886,False,False,NaN,BEARISH
2021-01-04 00:00:00,141.247,141.275,140.988,141.007,3577,False,False,BEARISH,BEARISH
...,...,...,...,...,...,...,...,...,...
2026-09-15 23:00:00,208.895,209.029,208.895,209.018,1853,True,False,BEARISH,BEARISH
2026-09-15 23:15:00,209.020,209.027,208.982,208.996,1268,False,False,BEARISH,BEARISH
2026-09-15 23:30:00,208.997,209.013,208.926,208.953,1279,False,False,BEARISH,BEARISH
2026-09-15 23:45:00,208.951,209.021,208.923,209.019,1261,False,False,BEARISH,BEARISH
2026-09-16 00:00:00,209.018,209.108,209.007,209.075,2780,False,False,BULLISH,BEARISH

In [8]:
# using m15 market structure for entry
def apply_total_signal(df, start_trade_hour=9, stop_trade_hour=19):
    # Initialize the 'TotalSignal' column
    df_signal_list = []

    for i in range(0, len(df)):
        current_bar_date = df.index[i]
        signal = 0

        # short
        # d1 trending conditions
        c_short_daily_direction = df['market_state_d1'].iloc[i-1] == 'BEARISH'
        if c_short_daily_direction:
            c_m15_ms_bearish = df['market_state'].iloc[i] == 'BEARISH'

            c_time_trade = start_trade_hour <= current_bar_date.hour and current_bar_date.hour <= stop_trade_hour
            if c_time_trade and c_m15_ms_bearish:
                signal = 1

        # long
        c_long_daily_direction = df['market_state_d1'].iloc[i-1] == 'BULLISH'
        if c_long_daily_direction:
            c_m15_ms_bullish = df['market_state'].iloc[i] == 'BULLISH'

            c_time_trade = start_trade_hour <= current_bar_date.hour and current_bar_date.hour <= stop_trade_hour
            if c_time_trade and c_m15_ms_bullish:
                signal = 2

        df_signal_list.append(signal)

    return df_signal_list

df_m15['TotalSignal'] = apply_total_signal(df=df_m15, start_trade_hour=9, stop_trade_hour=19)

In [9]:
len(df_m15[df_m15.TotalSignal != 0])

32481

In [10]:
df_m15['pointpos'] = df_m15.apply(lambda row: Util.pointpos(row), axis=1)

In [11]:
start_date_chart = '2022-10-1 00:00'
end_date_chart = '2022-10-30 00:00'
dfpl = df_m15.loc[start_date_chart : end_date_chart]#.set_index("Gmt time")

# Create a plot with 2 rows
fig = make_subplots(rows=1, cols=1)

# Add candlestick plot on the first row
fig.add_trace(go.Candlestick(x=dfpl.index,
                             open=dfpl['Open'],
                             high=dfpl['High'],
                             low=dfpl['Low'],
                             close=dfpl['Close']),
              row=1, col=1)

# Add markers for entry point m15
fig.add_trace(go.Scatter(x=dfpl.index, y=dfpl['pointpos'], mode="markers",
                         marker=dict(size=12, color="MediumPurple"),
                         name="entry"),
              row=1, col=1)

fig.update_layout(width=1500, height=800, sliders=[])
fig.show()

In [12]:
class ChochStrat(Strategy):
    mysize = 0.5
    slcoef = 2
    TPcoef = 2
    risk_percent = 0.01
    setup_duration_gap = 60
    stoploss_window = 150
    
    def init(self):
        self.current_day = None
        self.setup_duration = None
        self.order_placed_time = None

        super().init()

    def reset_order(self, current_bar_date):
        self.current_day = current_bar_date

        # delete placed order at the end of the day if not executed
        for order in self.orders:
            order_executed= False
            for trade in self.trades:
                if trade.tag == order.tag:
                    order_executed = True

            if order_executed == False:
                order.cancel()

        self.order_placed_time = None
        
    def get_tag(self):
        return f"{self.order_placed_time}"

    def get_highest_high(self):
            return self.data.High[len(self.data.High) - self.stoploss_window : len(self.data.High)].max()
        
    def get_lowest_low(self):
        return self.data.Low[len(self.data.Low) - self.stoploss_window : len(self.data.Low)].min()
    
    def next(self):
        super().next()

        current_bar_date = self.data.index[-1].date()
        if self.current_day != current_bar_date:
            self.reset_order(current_bar_date)

        if len(self.trades)==0:
            if self.data['TotalSignal'][-1]==1:
                planned_entry_price = self.data.Close[-1]
                sl = abs(planned_entry_price - self.get_highest_high())
                if sl == 0:
                    sl = round(random.uniform(0.3,1), 1)
                tp = self.TPcoef * sl

                sl1 = planned_entry_price + sl
                tp1 = planned_entry_price - tp
                position_size = int((self.risk_percent * self.equity) / sl)

                self.sell(sl=sl1, tp=tp1, size=position_size)
                
            if self.data['TotalSignal'][-1]==2:
                planned_entry_price = self.data.Close[-1]
                sl = abs(planned_entry_price - self.get_lowest_low())
                if sl == 0:
                    sl = round(random.uniform(0.3,1), 1)
                tp = self.TPcoef * sl

                sl1 = planned_entry_price - sl
                tp1 = planned_entry_price + tp
                position_size = int((self.risk_percent * self.equity) / sl)

                self.buy(sl=sl1, tp=tp1, size=position_size)

In [13]:
start_date_chart = '2021-1-1 00:00'
end_date_chart = '2026-12-30 00:00'
global_dfopt = df_m15.loc[start_date_chart : end_date_chart]

bt = Backtest(global_dfopt, ChochStrat, cash=10000, margin=0.005, finalize_trades=True) #0.0002
stats = bt.run()

print(stats)
bt.plot()

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=14076: Broker canceled the order due to insufficient margin (equity=9025.54, margin_available=9025.54).
  warnings.warn(

Start                     2021-01-03 23:00:00
End                       2026-09-16 00:00:00
Duration                   2081 days 01:00:00
Exposure Time [%]                    93.33804
Equity Final [$]                     9290.274
Equity Peak [$]                     11510.695
Return [%]                           -7.09726
Buy & Hold Return [%]                48.17505
Return (Ann.) [%]                     -1.1492
Volatility (Ann.) [%]                  9.3691
CAGR [%]                             -1.28376
Sharpe Ratio                         -0.12266
Sortino Ratio                        -0.16811
Calmar Ratio                         -0.04655
Alpha [%]                           -10.82243
Beta                                  0.07733
Max. Drawdown [%]                   -24.68731
Avg. Drawdown [%]                    -0.67535
Max. Drawdown Duration     1235 days 16:00:00
Avg. Drawdown Duration       19 days 22:58:00
# Trades                                  289
Win Rate [%]                         33.21799
Best Trade [%]                        4.36809
Worst Trade [%]                      -4.95726
Avg. Trade [%]                       -0.07676
Max. Trade Duration         118 days 21:45:00
Avg. Trade Duration           6 days 17:44:00
Profit Factor                         0.87189
Expectancy [%]                       -0.06797
SQN                                  -0.30503
Kelly Criterion                      -0.01295
_strategy                          ChochStrat
_equity_curve                             ...
_trades                        Size  Entry...
dtype: object

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\_plotting.py:141: UserWarning: Data contains too many candlesticks to plot; downsampling to '8h'. See `Backtest.plot(resample=...)`
  warnings.warn(f"Data contains too many candlesticks to plot; downsampling to {freq!r}. "

GridPlot(id='p1261', ...)

In [14]:
# add some sl tp management

class RandomStrat(Strategy):
    mysize = 0.5
    slcoef = 2
    TPcoef = 2
    risk_percent = 0.01
    trades_list = None
    stoploss_window = 150

    def is_signal(self, date):
        for i in range(0, len(self.trades_list)):
            if self.trades_list[i] == date:
                return True
        return False

    def get_highest_high(self):
        return self.data.High[len(self.data.High) - self.stoploss_window : len(self.data.High)].max()
    
    def get_lowest_low(self):
        return self.data.Low[len(self.data.Low) - self.stoploss_window : len(self.data.Low)].min()
    
    def init(self):
        super().init()

    def next(self):
        super().next()
        if self.is_signal(self.data.index[-1]) and len(self.trades) == 0 and len(self.closed_trades) < 289:
            if self.data['market_state_d1'][-1] == 'BULLISH':
                planned_entry_price = self.data.Close[-1]
                sl = abs(planned_entry_price - self.get_lowest_low())
                if sl == 0:
                    sl = round(random.uniform(0.3,1), 1)
                tp = self.TPcoef * sl

                sl1 = planned_entry_price - sl
                tp1 = planned_entry_price + tp
                position_size = int((self.risk_percent * self.equity) / sl)
                # max_affordable_size = int((self.equity * 0.99) / planned_entry_price)
                # print(f'{position_size} {max_affordable_size}')

                self.buy(sl=sl1, tp=tp1, size=position_size)
            else:
                planned_entry_price = self.data.Close[-1]
                sl = abs(planned_entry_price - self.get_highest_high())
                if sl == 0:
                    sl = round(random.uniform(0.3,1), 1)
                tp = self.TPcoef * sl

                sl1 = planned_entry_price + sl
                tp1 = planned_entry_price - tp
                position_size = int((self.risk_percent * self.equity) / sl)
                # max_affordable_size = int((self.equity * 0.99) / planned_entry_price)
                # print(f'{position_size} {max_affordable_size}')

                self.sell(sl=sl1, tp=tp1, size=position_size)

In [17]:
trades_list = []
while len(trades_list) != 700:
    random_index = randint(0, len(df_m15))
    candle = df_m15.iloc[random_index]
    # exclu Saturday and Sunday
    if candle.name.weekday() < 5:
        if 9 <= candle.name.hour and candle.name.hour <= 19:
            trades_list.append(candle.name)
trades_list.sort()

bt = Backtest(df_m15, RandomStrat, cash=10000, margin=0.005, finalize_trades=True) #0.0002
stats = bt.run(trades_list=trades_list)

print(stats)

bt.plot()

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=29538: Broker canceled the order due to insufficient margin (equity=9760.62, margin_available=9760.62).
  warnings.warn(
c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=113238: Broker canceled the order due to insufficient margin (equity=11504.64, margin_available=11504.64).
  warnings.warn(

Start                     2021-01-03 23:00:00
End                       2026-09-16 00:00:00
Duration                   2081 days 01:00:00
Exposure Time [%]                    65.78492
Equity Final [$]                    10170.746
Equity Peak [$]                     11739.798
Return [%]                            1.70746
Buy & Hold Return [%]                48.17505
Return (Ann.) [%]                     0.26618
Volatility (Ann.) [%]                 8.03642
CAGR [%]                              0.29759
Sharpe Ratio                          0.03312
Sortino Ratio                         0.04858
Calmar Ratio                           0.0178
Alpha [%]                            -0.42501
Beta                                  0.04426
Max. Drawdown [%]                   -14.95481
Avg. Drawdown [%]                    -0.50626
Max. Drawdown Duration     1285 days 09:00:00
Avg. Drawdown Duration       15 days 14:31:00
# Trades                                  221
Win Rate [%]                         34.38914
Best Trade [%]                         5.7798
Worst Trade [%]                      -5.16268
Avg. Trade [%]                       -0.05535
Max. Trade Duration          74 days 00:30:00
Avg. Trade Duration           6 days 06:05:00
Profit Factor                         0.89509
Expectancy [%]                        -0.0477
SQN                                   0.07907
Kelly Criterion                       0.00387
_strategy                 RandomStrat(trad...
_equity_curve                             ...
_trades                        Size  Entry...
dtype: object

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\_plotting.py:141: UserWarning: Data contains too many candlesticks to plot; downsampling to '8h'. See `Backtest.plot(resample=...)`
  warnings.warn(f"Data contains too many candlesticks to plot; downsampling to {freq!r}. "

GridPlot(id='p1829', ...)

In [19]:
i = 0
expectancy_list = []
winrate_list = []
number_trades = []

while len(expectancy_list) < 500:
    trades_list = []
    while len(trades_list) != 700:
        random_index = randint(0, len(df_m15)-1)
        candle = df_m15.iloc[random_index -1]
        # exclu Saturday and Sunday
        if candle.name.weekday() < 5:
            if 9 <= candle.name.hour and candle.name.hour <= 19:
                trades_list.append(candle.name)
    trades_list.sort()

    bt = Backtest(df_m15, RandomStrat, cash=10000, margin=0.0009, finalize_trades=True) #0.0002
    stats = bt.run(trades_list=trades_list)
    if 200 <= stats['# Trades'] and stats['# Trades'] <= 340:
        expectancy_list.append(stats['Expectancy [%]'])
        winrate_list.append(stats['Win Rate [%]'])
        number_trades.append(stats['# Trades'])
        print(f'{i} {len(expectancy_list)} {stats['Expectancy [%]']} Done')
    i += 1

print(expectancy_list)

0 1 -0.05025464773836021 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=26794: Broker canceled the order due to insufficient margin (equity=10152.36, margin_available=10152.36).
  warnings.warn(

1 2 -0.04287313200611774 Done
2 3 -0.015322464792428311 Done
3 4 -0.05961390139549315 Done
4 5 -0.004706843416911728 Done
5 6 -0.01878648361787807 Done
6 7 0.010241153841035898 Done
7 8 -0.03589121806386217 Done
8 9 -0.088136280835197 Done
9 10 -0.05285384835711022 Done
10 11 0.0290503747680437 Done
11 12 -0.06952464372535219 Done
12 13 0.052920744875391786 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=35667: Broker canceled the order due to insufficient margin (equity=8926.71, margin_available=8926.71).
  warnings.warn(

13 14 -0.060876652751879846 Done
14 15 0.01574338341644563 Done
15 16 -0.09817417441233599 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=91438: Broker canceled the order due to insufficient margin (equity=11017.11, margin_available=11017.11).
  warnings.warn(

16 17 -0.04212848648010188 Done
17 18 -0.03986046413913987 Done
18 19 -0.022513803656238313 Done
19 20 -0.11672644154411263 Done
20 21 -0.12336428076954947 Done
21 22 -0.09248404100372394 Done
22 23 0.024288848144226258 Done
23 24 -0.04354631796301506 Done
24 25 0.06352415417740101 Done
25 26 -0.010634571473672067 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=73951: Broker canceled the order due to insufficient margin (equity=8965.54, margin_available=8965.54).
  warnings.warn(

26 27 -0.0662210754128031 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=35667: Broker canceled the order due to insufficient margin (equity=9910.45, margin_available=9910.45).
  warnings.warn(
c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=51390: Broker canceled the order due to insufficient margin (equity=9516.35, margin_available=9516.35).
  warnings.warn(

27 28 -0.08463311421652964 Done
28 29 0.008473025092570726 Done
29 30 -0.021337505172589255 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=137617: Broker canceled the order due to insufficient margin (equity=11812.67, margin_available=11812.67).
  warnings.warn(

30 31 -0.016868081423122645 Done
31 32 -0.021864255663597353 Done
32 33 -0.009600125030552766 Done
33 34 0.01793330859729453 Done
34 35 -0.06333048113838684 Done
35 36 -0.15193312007990098 Done
36 37 -0.04402439511013108 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=91438: Broker canceled the order due to insufficient margin (equity=11971.28, margin_available=11971.28).
  warnings.warn(

37 38 -0.07982882460939641 Done
38 39 -0.06927327631162664 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=35667: Broker canceled the order due to insufficient margin (equity=9395.37, margin_available=9395.37).
  warnings.warn(

39 40 -0.08884643671547528 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=73031: Broker canceled the order due to insufficient margin (equity=11174.14, margin_available=11174.14).
  warnings.warn(
c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=96933: Broker canceled the order due to insufficient margin (equity=13583.09, margin_available=13583.09).
  warnings.warn(

40 41 0.021798987185575422 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=5369: Broker canceled the order due to insufficient margin (equity=10503.86, margin_available=10503.86).
  warnings.warn(

41 42 -0.07046758812410568 Done
42 43 -0.15219686519113837 Done
43 44 -0.19158524337500488 Done
44 45 -0.0660069610455602 Done
45 46 -0.08381793365574568 Done
46 47 0.00582518940670837 Done
47 48 -0.0022975530740464096 Done
48 49 -0.04372716520726314 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=72211: Broker canceled the order due to insufficient margin (equity=8608.05, margin_available=8608.05).
  warnings.warn(

49 50 -0.09027827306133149 Done
50 51 -0.08027820032343946 Done
51 52 -0.02257659646971716 Done
52 53 -0.029214721945115325 Done
53 54 -0.11705292078633346 Done
54 55 -0.03581771521125908 Done
55 56 -0.08718899049183813 Done
56 57 -0.08504866520527632 Done
57 58 -0.0040339507738484754 Done
58 59 -0.0950336699429815 Done
59 60 -0.02671851401308458 Done
60 61 -0.0445221997726447 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=63758: Broker canceled the order due to insufficient margin (equity=8394.36, margin_available=8394.36).
  warnings.warn(

61 62 -0.05051223560649222 Done
62 63 -0.11511440760696642 Done
63 64 -0.10143790026117439 Done
64 65 -0.05238953516686185 Done
65 66 0.003219706621036853 Done
66 67 0.06828999673920616 Done
67 68 -0.05643986909301643 Done
68 69 0.07589658130382902 Done
69 70 -0.044240770461465365 Done
70 71 -0.05058904308185677 Done
71 72 -0.09311058062261632 Done
72 73 -0.01737053425504964 Done
73 74 -0.0075741369002145864 Done
74 75 -0.009378372372613684 Done
75 76 -0.06424912212024785 Done
76 77 -0.06021305753297361 Done
77 78 -0.08458325908070012 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=63758: Broker canceled the order due to insufficient margin (equity=10923.21, margin_available=10923.21).
  warnings.warn(

78 79 -0.010080482048421274 Done
79 80 0.05034129774811192 Done
80 81 -0.08439308008406904 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=79072: Broker canceled the order due to insufficient margin (equity=7190.23, margin_available=7190.23).
  warnings.warn(

81 82 -0.09749026306489188 Done
82 83 -0.04997910239844745 Done
83 84 -0.05440026676964678 Done
84 85 -0.08670527371888148 Done
85 86 -0.020386036463529045 Done
86 87 -0.1851227085038971 Done
87 88 -0.037959170415315956 Done
88 89 -0.04727017584398055 Done
89 90 0.018378062806549477 Done
90 91 -0.020501541257739616 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=137815: Broker canceled the order due to insufficient margin (equity=8437.56, margin_available=8437.56).
  warnings.warn(

91 92 -0.01594536586950227 Done
92 93 -0.0031977539736298957 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=98207: Broker canceled the order due to insufficient margin (equity=13690.67, margin_available=13690.67).
  warnings.warn(

93 94 -0.004245342409040167 Done
94 95 -0.0966184638750656 Done
95 96 -0.05083589554485392 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=96933: Broker canceled the order due to insufficient margin (equity=8456.76, margin_available=8456.76).
  warnings.warn(

96 97 -0.0806944343997135 Done
97 98 -0.004549110069201262 Done
98 99 -0.02566451503592363 Done
99 100 -0.00681381044428287 Done
100 101 -0.08572398101096336 Done
101 102 -0.11115086033205214 Done
102 103 -0.0642372191213675 Done
103 104 0.08725721036177887 Done
104 105 -0.046861144155240134 Done
105 106 -0.023914591552785837 Done
106 107 -0.051056509800367675 Done
107 108 -0.0013836810880253976 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=98231: Broker canceled the order due to insufficient margin (equity=11188.31, margin_available=11188.31).
  warnings.warn(

108 109 -0.09040162842723776 Done
109 110 -0.016978068215046486 Done
110 111 -0.05590517720481991 Done
111 112 -0.07925070317394196 Done
112 113 -0.07538663920929288 Done
113 114 -0.02041391222710502 Done
114 115 0.10963342416583462 Done
115 116 -0.045763627224424515 Done
116 117 -0.07001395219115539 Done
117 118 -0.07174008979751655 Done
118 119 -0.08811166697763038 Done
119 120 -0.048954511745603134 Done
120 121 0.01100692265685474 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=35667: Broker canceled the order due to insufficient margin (equity=10440.92, margin_available=10440.92).
  warnings.warn(

121 122 -0.027787632039075656 Done
122 123 -0.0581997910125879 Done
123 124 -0.010372571224970352 Done
124 125 0.02480128875295191 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=43140: Broker canceled the order due to insufficient margin (equity=10515.02, margin_available=10515.02).
  warnings.warn(

125 126 -0.0305698494915063 Done
126 127 -0.13941986813382934 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=91438: Broker canceled the order due to insufficient margin (equity=10113.46, margin_available=10113.46).
  warnings.warn(

127 128 0.03809457345139957 Done
128 129 -0.09110117199774917 Done
129 130 -0.011187456493551524 Done
130 131 -0.017886982128656224 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=98231: Broker canceled the order due to insufficient margin (equity=13134.09, margin_available=13134.09).
  warnings.warn(

131 132 -0.03603517263192953 Done
132 133 -0.072693405948772 Done
133 134 0.026430051358666787 Done
134 135 -0.10236976280990864 Done
135 136 -0.016288369403458076 Done
136 137 -0.024741260777363498 Done
137 138 0.02976689517935899 Done
138 139 -0.06339038118551643 Done
139 140 -0.08242029595027049 Done
140 141 -0.06287747396703129 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=137796: Broker canceled the order due to insufficient margin (equity=6622.65, margin_available=6622.65).
  warnings.warn(

141 142 -0.10814392031150151 Done
142 143 -0.0948707364467846 Done
143 144 -0.0826411298535465 Done
144 145 -0.009671378097598937 Done
145 146 -0.024415186150573486 Done
146 147 0.011135298550603547 Done
147 148 -0.08981045445662572 Done
148 149 -0.0123171651591938 Done
149 150 -0.03377302482786842 Done
150 151 -0.05450499926370249 Done
151 152 -0.05582563937744182 Done
152 153 -0.0032200451048505834 Done
153 154 -0.017721163745443344 Done
154 155 -0.03923386381271729 Done
155 156 -0.06702063422742383 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=35667: Broker canceled the order due to insufficient margin (equity=10563.14, margin_available=10563.14).
  warnings.warn(

156 157 0.010713564544117841 Done
157 158 -0.022580357283902442 Done
158 159 -0.004290500428379275 Done
159 160 -0.061337248303377015 Done
160 161 -0.14756223032455362 Done
161 162 -0.07845991505943156 Done
162 163 0.062041682603696746 Done
163 164 -0.027323257748899578 Done
164 165 -0.06322411238030338 Done
165 166 -0.08380997959564201 Done
166 167 -0.10980626980167368 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=73031: Broker canceled the order due to insufficient margin (equity=8310.85, margin_available=8310.85).
  warnings.warn(

167 168 -0.07250713817440922 Done
168 169 0.04732886181079187 Done
169 170 -0.09587799164913477 Done
170 171 -0.007844497014934155 Done
171 172 -0.04670293313972423 Done
172 173 0.004185999276518121 Done
173 174 -0.0724721543797351 Done
174 175 0.007139720526881188 Done
175 176 -0.07976347411618204 Done
176 177 -0.020266287844608766 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=63758: Broker canceled the order due to insufficient margin (equity=8053.79, margin_available=8053.79).
  warnings.warn(

177 178 0.005201437930056369 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=63758: Broker canceled the order due to insufficient margin (equity=12560.48, margin_available=12560.48).
  warnings.warn(

178 179 -0.04029484972945179 Done
179 180 -0.11887849617506095 Done
180 181 -0.06020868417866182 Done
181 182 -0.05629432551631284 Done
182 183 -0.020779981110898717 Done
183 184 0.046150790561033744 Done
184 185 -0.01224682109776882 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=35667: Broker canceled the order due to insufficient margin (equity=9525.54, margin_available=9525.54).
  warnings.warn(

185 186 -0.06982363902231106 Done
186 187 -0.09130779372725122 Done
187 188 -0.043679205957262233 Done
188 189 -0.0784262992048399 Done
189 190 -0.021213933585984 Done
190 191 -0.014546552551957264 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=85284: Broker canceled the order due to insufficient margin (equity=8722.40, margin_available=8722.40).
  warnings.warn(

191 192 0.010164522391669279 Done
192 193 -0.03929073725020686 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=98207: Broker canceled the order due to insufficient margin (equity=11627.65, margin_available=11627.65).
  warnings.warn(

193 194 -0.03521693209938525 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=91438: Broker canceled the order due to insufficient margin (equity=11244.35, margin_available=11244.35).
  warnings.warn(

194 195 -0.07306453585471898 Done
195 196 0.04940175179999538 Done
196 197 -0.14998033892541093 Done
197 198 -0.05449504472036322 Done
198 199 -0.05994557960475229 Done
199 200 -0.09874570831896756 Done
200 201 0.02753573437681882 Done
201 202 0.014442107796838966 Done
202 203 -0.03850251439793405 Done
203 204 -0.01200067993122427 Done
204 205 0.030497218900658 Done
205 206 -0.013414523437247895 Done
206 207 -0.0963238236934639 Done
207 208 0.004486858887233135 Done
208 209 -0.12524173798892402 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=69550: Broker canceled the order due to insufficient margin (equity=8377.72, margin_available=8377.72).
  warnings.warn(
c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=137796: Broker canceled the order due to insufficient margin (equity=7742.89, margin_available=7742.89).
  warnings.warn(

209 210 -0.014513235797941351 Done
210 211 -0.019938995152158343 Done
211 212 -0.07731085946621159 Done
212 213 -0.06259745809905892 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=91438: Broker canceled the order due to insufficient margin (equity=8504.73, margin_available=8504.73).
  warnings.warn(

213 214 -0.0015560586318329604 Done
214 215 -0.05821767689668397 Done
215 216 -0.0649368605196574 Done
216 217 0.045762799308022926 Done
217 218 -0.031493150661883004 Done
218 219 -0.09724974226322124 Done
219 220 0.01816287903816217 Done
220 221 -0.11004902764587451 Done
221 222 -0.06516894935334343 Done
222 223 -0.044649719878160354 Done
223 224 0.035223470742109415 Done
224 225 -0.019389933972995474 Done
225 226 -0.1311662757614468 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=98207: Broker canceled the order due to insufficient margin (equity=8402.73, margin_available=8402.73).
  warnings.warn(

226 227 -0.05545131928619162 Done
227 228 -0.12540498015699506 Done
228 229 -0.12092465176946643 Done
229 230 -0.004722145774752151 Done
230 231 -0.09174855897301654 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=85285: Broker canceled the order due to insufficient margin (equity=12131.09, margin_available=12131.09).
  warnings.warn(
c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=98207: Broker canceled the order due to insufficient margin (equity=12425.19, margin_available=12425.19).
  warnings.warn(

231 232 -0.009079633643952608 Done
232 233 -0.06090402736109961 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=51390: Broker canceled the order due to insufficient margin (equity=11500.11, margin_available=11500.11).
  warnings.warn(

233 234 -0.021868073070384717 Done
234 235 -0.07591437333427978 Done
235 236 0.008111748257999494 Done
236 237 0.02688246113473673 Done
237 238 0.04051622704095946 Done
238 239 -0.06970098513709962 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=69550: Broker canceled the order due to insufficient margin (equity=10366.81, margin_available=10366.81).
  warnings.warn(

239 240 -0.02941729046905483 Done
240 241 -0.014916036390017089 Done
241 242 -0.03646718323453486 Done
242 243 0.0517804695370356 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=85285: Broker canceled the order due to insufficient margin (equity=9228.09, margin_available=9228.09).
  warnings.warn(

243 244 -0.11613480052255831 Done
244 245 -0.05346941798020227 Done
245 246 -0.043682140990055685 Done
246 247 0.00035636600338035475 Done
247 248 -0.0745966390362518 Done
248 249 -0.1066034916063068 Done
249 250 -0.05686830768602849 Done
250 251 -0.022027567790689682 Done
251 252 -0.05303277565147434 Done
252 253 -0.004957099975900235 Done
253 254 -0.02398004049379375 Done
254 255 -0.06996961328886202 Done
255 256 -0.07522899076736324 Done
256 257 -0.02525383330260957 Done
257 258 -0.04616775031040422 Done
258 259 -0.045136093788658085 Done
259 260 -0.061449576924603726 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=123901: Broker canceled the order due to insufficient margin (equity=7318.71, margin_available=7318.71).
  warnings.warn(

260 261 -0.17766466318122143 Done
261 262 -0.054927583218246506 Done
262 263 -0.030971811701907548 Done
263 264 -0.08905102594340393 Done
264 265 -0.10072267687766079 Done
265 266 -0.04597352044027078 Done
266 267 -0.05823125343834896 Done
267 268 -0.10992520853862202 Done
269 269 -0.04938057823195861 Done
270 270 -0.027422652081552323 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=53676: Broker canceled the order due to insufficient margin (equity=8754.83, margin_available=8754.83).
  warnings.warn(
c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=79072: Broker canceled the order due to insufficient margin (equity=9811.64, margin_available=9811.64).
  warnings.warn(

271 271 -0.03280775516437554 Done
272 272 -0.004861770230134826 Done
273 273 -0.04802240662658634 Done
274 274 -0.056945200936615314 Done
275 275 -0.06384701755858775 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=139111: Broker canceled the order due to insufficient margin (equity=5501.75, margin_available=5501.75).
  warnings.warn(

276 276 -0.13575640802931077 Done
277 277 -0.0914786669440572 Done
278 278 0.013521466914767214 Done
279 279 -0.06611404164991169 Done
280 280 -0.1897746168878798 Done
281 281 -0.09448355746567223 Done
282 282 -0.015270608012226013 Done
283 283 -0.1554415933653023 Done
284 284 -0.03920334894223969 Done
285 285 -0.031768426700801315 Done
286 286 -0.0318428874647042 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=79072: Broker canceled the order due to insufficient margin (equity=9757.64, margin_available=9757.64).
  warnings.warn(

287 287 -0.028860508392027102 Done
288 288 -0.07963602344236678 Done
289 289 -0.06332615148026201 Done
290 290 -0.03659626032610565 Done
291 291 0.10360407415079434 Done
292 292 -0.012735509054224332 Done
293 293 -0.04821971225835991 Done
294 294 -0.020039985407492317 Done
295 295 -0.09509945438401261 Done
296 296 -0.09813745563860914 Done
297 297 0.00847902582742533 Done
298 298 -0.029609030218957316 Done
299 299 -0.055593540852358216 Done
300 300 -0.020822965229547588 Done
301 301 -0.03305767196155632 Done
302 302 -0.11010763788071791 Done
303 303 1.3411606208087613e-05 Done
304 304 0.010969379263671588 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=96933: Broker canceled the order due to insufficient margin (equity=11068.16, margin_available=11068.16).
  warnings.warn(

305 305 -0.12196878609159638 Done
306 306 -0.01816173707342655 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=53676: Broker canceled the order due to insufficient margin (equity=10020.11, margin_available=10020.11).
  warnings.warn(

307 307 -0.04232648636421723 Done
308 308 -0.0953931559354229 Done
309 309 -0.19222577636834565 Done
310 310 -0.10667375017585959 Done
311 311 -0.05682612130699701 Done
312 312 -0.034483872204871396 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=90295: Broker canceled the order due to insufficient margin (equity=8733.78, margin_available=8733.78).
  warnings.warn(

313 313 -0.0496386241908731 Done
314 314 -0.07977515854249595 Done
315 315 -0.054757157351502946 Done
316 316 -0.08727579593553557 Done
317 317 -0.03305664152137441 Done
318 318 -0.09346822678591166 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=91438: Broker canceled the order due to insufficient margin (equity=12237.06, margin_available=12237.06).
  warnings.warn(

319 319 -0.019500169718985643 Done
320 320 -0.0772510805554405 Done
321 321 -0.08296241905526192 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=134287: Broker canceled the order due to insufficient margin (equity=9410.00, margin_available=9410.00).
  warnings.warn(

322 322 0.006709527621046634 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=35667: Broker canceled the order due to insufficient margin (equity=10990.45, margin_available=10990.45).
  warnings.warn(

323 323 -0.016707923608196607 Done
324 324 -0.03226324044828507 Done
325 325 -0.07068444541302996 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=91438: Broker canceled the order due to insufficient margin (equity=9330.08, margin_available=9330.08).
  warnings.warn(

326 326 -0.07791937752955462 Done
327 327 -0.032985520088608535 Done
328 328 -0.03822164831218085 Done
329 329 -0.007773819519753829 Done
330 330 0.032125432098092106 Done
331 331 -0.0817773643745616 Done
332 332 0.0028397107482230105 Done
333 333 -0.05976287181081952 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=69550: Broker canceled the order due to insufficient margin (equity=9206.55, margin_available=9206.55).
  warnings.warn(

334 334 0.010888422349083042 Done
335 335 -0.01068940061716873 Done
336 336 -0.038517799499887394 Done
337 337 -0.055487079721303685 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=5369: Broker canceled the order due to insufficient margin (equity=10598.17, margin_available=10598.17).
  warnings.warn(

338 338 0.028531357248941923 Done
339 339 -0.11055205867270072 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=73031: Broker canceled the order due to insufficient margin (equity=13024.76, margin_available=13024.76).
  warnings.warn(

340 340 -0.005872987424603938 Done
341 341 0.03329926858321813 Done
342 342 -0.05644538019345216 Done
343 343 -0.1081654888451135 Done
344 344 -0.0026251508438233824 Done
345 345 -0.046805768620181966 Done
346 346 -0.04261872745284275 Done
347 347 -0.0018704078983764897 Done
348 348 -0.026573487436771473 Done
349 349 -0.08074203562944239 Done
350 350 0.004712937508009891 Done
351 351 -0.0629714936667456 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=139111: Broker canceled the order due to insufficient margin (equity=13057.41, margin_available=13057.41).
  warnings.warn(

352 352 -0.006519345548090335 Done
353 353 -0.08357516294925312 Done
354 354 -0.0569701565726158 Done
355 355 0.059753572151412186 Done
356 356 -0.1062691635775007 Done
357 357 -0.03942635105866485 Done
358 358 -0.07073713741541411 Done
359 359 -0.0813770206019642 Done
360 360 -0.10125627422194806 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=73031: Broker canceled the order due to insufficient margin (equity=10044.66, margin_available=10044.66).
  warnings.warn(

361 361 -0.07307444933786486 Done
362 362 -0.0845229328080958 Done
363 363 0.00774235439365229 Done
364 364 -0.020614649125949847 Done
365 365 -0.06962569816409585 Done
366 366 -0.019459633364931582 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=96933: Broker canceled the order due to insufficient margin (equity=11511.56, margin_available=11511.56).
  warnings.warn(

367 367 -0.013185105598167777 Done
368 368 -0.014689229746516557 Done
369 369 -0.047425605574025684 Done
370 370 -0.13350484333942703 Done
371 371 -0.06046292501721216 Done
372 372 -0.0441768636438871 Done
373 373 0.031713529812447225 Done
374 374 -0.12121019012865329 Done
375 375 0.011700659706314422 Done
376 376 0.010644091322244604 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=73031: Broker canceled the order due to insufficient margin (equity=10637.69, margin_available=10637.69).
  warnings.warn(

377 377 -0.10447673622087565 Done
378 378 -0.02842203453920172 Done
379 379 -0.08564788409245665 Done
380 380 -0.06973374160724437 Done
381 381 -0.1141762162128481 Done
382 382 -0.1351058518178057 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=5369: Broker canceled the order due to insufficient margin (equity=11139.72, margin_available=11139.72).
  warnings.warn(
c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=90295: Broker canceled the order due to insufficient margin (equity=9080.36, margin_available=9080.36).
  warnings.warn(

383 383 -0.030142510287035906 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=101263: Broker canceled the order due to insufficient margin (equity=12049.87, margin_available=12049.87).
  warnings.warn(

384 384 0.021854028483012357 Done
385 385 -0.056162419606465785 Done
386 386 0.02330766084025071 Done
387 387 -0.04422199394151744 Done
388 388 0.02393748866012628 Done
389 389 -0.056368165853322647 Done
390 390 -0.029498024940143867 Done
391 391 -0.02502081145406512 Done
392 392 -0.07499608537512643 Done
393 393 -0.0737671750786416 Done
394 394 -0.024230858317958917 Done
395 395 -0.052078451518074206 Done
396 396 -0.056157405214966816 Done
397 397 -0.05416296795447938 Done
398 398 -0.09145128607106111 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=72211: Broker canceled the order due to insufficient margin (equity=9005.33, margin_available=9005.33).
  warnings.warn(
c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=85285: Broker canceled the order due to insufficient margin (equity=9231.08, margin_available=9231.08).
  warnings.warn(

399 399 -0.0666162374915011 Done
400 400 -0.027135736220274893 Done
401 401 -0.05582207674111619 Done
402 402 -0.05912066186934789 Done
403 403 -0.0964533369133099 Done
404 404 -0.028740491048453245 Done
405 405 -0.13097037058490785 Done
406 406 -0.06528387951068383 Done
407 407 -0.04048294184104075 Done
408 408 -0.10336676355510975 Done
409 409 -0.1011569885386048 Done
410 410 -0.012571914500971148 Done
411 411 -0.026306354804037247 Done
412 412 -0.1082950416358244 Done
413 413 0.0008296042404396681 Done
414 414 -0.11291107191866508 Done
415 415 -0.04764690067665812 Done
416 416 -0.051324001858901624 Done
417 417 -0.008290362092514603 Done
418 418 -0.18343666074585532 Done
419 419 -0.07186311660034814 Done
420 420 -0.04693566644937885 Done
421 421 -0.07455595601205463 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=35667: Broker canceled the order due to insufficient margin (equity=9592.08, margin_available=9592.08).
  warnings.warn(

422 422 -0.013113633322292366 Done
423 423 0.07144095613245151 Done
424 424 0.002676950185171127 Done
425 425 -0.042768207757932775 Done
426 426 -0.06910072134473007 Done
427 427 -0.0448352320096831 Done
428 428 -0.0908931958641247 Done
429 429 -0.005144476438220859 Done
430 430 -0.05180102883662871 Done
431 431 -0.07457003805408628 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=69550: Broker canceled the order due to insufficient margin (equity=10131.88, margin_available=10131.88).
  warnings.warn(

432 432 -0.07425500955130743 Done
433 433 -0.09386287335804758 Done
434 434 -0.10577180595581781 Done
435 435 -0.09516626258699383 Done
436 436 -0.07684683973310522 Done
437 437 -0.032456582462244254 Done
438 438 -0.03736370338460993 Done
439 439 0.01180185228588144 Done
440 440 0.017607156614857216 Done
441 441 -0.0010888442312893423 Done
442 442 -0.03655615485343998 Done
443 443 -0.16866536168117172 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=53676: Broker canceled the order due to insufficient margin (equity=9131.54, margin_available=9131.54).
  warnings.warn(

444 444 -0.02205544106018076 Done
445 445 -0.12224379310415648 Done
446 446 -0.15495428982070916 Done
447 447 -0.07945642643762599 Done
448 448 -0.07212206904077184 Done
449 449 -0.0733890337852878 Done
450 450 -0.04568178271814095 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=43140: Broker canceled the order due to insufficient margin (equity=10803.07, margin_available=10803.07).
  warnings.warn(

451 451 -0.09466515696012848 Done
452 452 -0.015112285827103247 Done
453 453 -0.06741020091467391 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=67628: Broker canceled the order due to insufficient margin (equity=10472.29, margin_available=10472.29).
  warnings.warn(

454 454 -0.09240620371930293 Done
455 455 -0.05129151698533862 Done
456 456 -0.09335958698641883 Done
457 457 -0.0437270199411043 Done
458 458 -0.08071832149806278 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=9256: Broker canceled the order due to insufficient margin (equity=9788.68, margin_available=9788.68).
  warnings.warn(

459 459 0.008206477746772942 Done
460 460 -0.022410714547569325 Done
461 461 -0.038776715507428214 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=73951: Broker canceled the order due to insufficient margin (equity=10392.12, margin_available=10392.12).
  warnings.warn(

462 462 -0.06757286120853845 Done
463 463 -0.09514165092571573 Done
464 464 -0.029970412076291343 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=26794: Broker canceled the order due to insufficient margin (equity=10898.09, margin_available=10898.09).
  warnings.warn(

466 465 -0.06392441360602226 Done
467 466 -0.07589043738841031 Done
468 467 -0.062248437746442134 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=85284: Broker canceled the order due to insufficient margin (equity=9293.14, margin_available=9293.14).
  warnings.warn(

469 468 -0.06859532075808915 Done
470 469 -0.07236398689041404 Done
471 470 0.0031889936933231127 Done
472 471 -0.05062739870863091 Done
473 472 -0.017399640385308855 Done
474 473 -0.024016142231002985 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=96933: Broker canceled the order due to insufficient margin (equity=10179.94, margin_available=10179.94).
  warnings.warn(

475 474 -0.08168349643110404 Done
476 475 -0.025258982776639818 Done
477 476 0.006470677718272269 Done
478 477 0.010572182239893318 Done
479 478 -0.01860299037583771 Done
480 479 -0.06096505839437115 Done
481 480 -0.08364841581399188 Done
482 481 -0.06246184401783331 Done
483 482 0.015843658137004137 Done
484 483 -0.01605707403071941 Done
485 484 -0.03922757786361558 Done
486 485 -0.07478770712345637 Done

c:\Users\kyanh\AppData\Local\Programs\Python\Python313-arm64\Lib\site-packages\backtesting\backtesting.py:1009: UserWarning: time=9256: Broker canceled the order due to insufficient margin (equity=10908.81, margin_available=10908.81).
  warnings.warn(

487 486 -0.01748507851646568 Done
488 487 -0.03239719501864659 Done
489 488 -0.13839161133353745 Done
490 489 0.03325447677809094 Done
491 490 -0.013043871522379263 Done
492 491 -0.0023090736446622403 Done
493 492 -0.02439984822525093 Done
494 493 0.07853308542329857 Done
495 494 0.0023470228361754083 Done
496 495 -0.029549757552540877 Done
497 496 0.011700941822724952 Done
498 497 -0.05834014071669797 Done
499 498 -0.10403730358633162 Done
500 499 -0.042435373930993045 Done
501 500 -0.0710083377265901 Done
[np.float64(-0.05025464773836021), np.float64(-0.04287313200611774), np.float64(-0.015322464792428311), np.float64(-0.05961390139549315), np.float64(-0.004706843416911728), np.float64(-0.01878648361787807), np.float64(0.010241153841035898), np.float64(-0.03589121806386217), np.float64(-0.088136280835197), np.float64(-0.05285384835711022), np.float64(0.0290503747680437), np.float64(-0.06952464372535219), np.float64(0.052920744875391786), np.float64(-0.060876652751879846), np.float64(0.01574338341644563), np.float64(-0.09817417441233599), np.float64(-0.04212848648010188), np.float64(-0.03986046413913987), np.float64(-0.022513803656238313), np.float64(-0.11672644154411263), np.float64(-0.12336428076954947), np.float64(-0.09248404100372394), np.float64(0.024288848144226258), np.float64(-0.04354631796301506), np.float64(0.06352415417740101), np.float64(-0.010634571473672067), np.float64(-0.0662210754128031), np.float64(-0.08463311421652964), np.float64(0.008473025092570726), np.float64(-0.021337505172589255), np.float64(-0.016868081423122645), np.float64(-0.021864255663597353), np.float64(-0.009600125030552766), np.float64(0.01793330859729453), np.float64(-0.06333048113838684), np.float64(-0.15193312007990098), np.float64(-0.04402439511013108), np.float64(-0.07982882460939641), np.float64(-0.06927327631162664), np.float64(-0.08884643671547528), np.float64(0.021798987185575422), np.float64(-0.07046758812410568), np.float64(-0.15219686519113837), np.float64(-0.19158524337500488), np.float64(-0.0660069610455602), np.float64(-0.08381793365574568), np.float64(0.00582518940670837), np.float64(-0.0022975530740464096), np.float64(-0.04372716520726314), np.float64(-0.09027827306133149), np.float64(-0.08027820032343946), np.float64(-0.02257659646971716), np.float64(-0.029214721945115325), np.float64(-0.11705292078633346), np.float64(-0.03581771521125908), np.float64(-0.08718899049183813), np.float64(-0.08504866520527632), np.float64(-0.0040339507738484754), np.float64(-0.0950336699429815), np.float64(-0.02671851401308458), np.float64(-0.0445221997726447), np.float64(-0.05051223560649222), np.float64(-0.11511440760696642), np.float64(-0.10143790026117439), np.float64(-0.05238953516686185), np.float64(0.003219706621036853), np.float64(0.06828999673920616), np.float64(-0.05643986909301643), np.float64(0.07589658130382902), np.float64(-0.044240770461465365), np.float64(-0.05058904308185677), np.float64(-0.09311058062261632), np.float64(-0.01737053425504964), np.float64(-0.0075741369002145864), np.float64(-0.009378372372613684), np.float64(-0.06424912212024785), np.float64(-0.06021305753297361), np.float64(-0.08458325908070012), np.float64(-0.010080482048421274), np.float64(0.05034129774811192), np.float64(-0.08439308008406904), np.float64(-0.09749026306489188), np.float64(-0.04997910239844745), np.float64(-0.05440026676964678), np.float64(-0.08670527371888148), np.float64(-0.020386036463529045), np.float64(-0.1851227085038971), np.float64(-0.037959170415315956), np.float64(-0.04727017584398055), np.float64(0.018378062806549477), np.float64(-0.020501541257739616), np.float64(-0.01594536586950227), np.float64(-0.0031977539736298957), np.float64(-0.004245342409040167), np.float64(-0.0966184638750656), np.float64(-0.05083589554485392), np.float64(-0.0806944343997135), np.float64(-0.004549110069201262), np.float64(-0.02566451503592363), np.float64(-0.00681381044428287), np.float64(-0.08572398101096336), np.float64(-0.11115086033205214), np.float64(-0.0642372191213675), np.float64(0.08725721036177887), np.float64(-0.046861144155240134), np.float64(-0.023914591552785837), np.float64(-0.051056509800367675), np.float64(-0.0013836810880253976), np.float64(-0.09040162842723776), np.float64(-0.016978068215046486), np.float64(-0.05590517720481991), np.float64(-0.07925070317394196), np.float64(-0.07538663920929288), np.float64(-0.02041391222710502), np.float64(0.10963342416583462), np.float64(-0.045763627224424515), np.float64(-0.07001395219115539), np.float64(-0.07174008979751655), np.float64(-0.08811166697763038), np.float64(-0.048954511745603134), np.float64(0.01100692265685474), np.float64(-0.027787632039075656), np.float64(-0.0581997910125879), np.float64(-0.010372571224970352), np.float64(0.02480128875295191), np.float64(-0.0305698494915063), np.float64(-0.13941986813382934), np.float64(0.03809457345139957), np.float64(-0.09110117199774917), np.float64(-0.011187456493551524), np.float64(-0.017886982128656224), np.float64(-0.03603517263192953), np.float64(-0.072693405948772), np.float64(0.026430051358666787), np.float64(-0.10236976280990864), np.float64(-0.016288369403458076), np.float64(-0.024741260777363498), np.float64(0.02976689517935899), np.float64(-0.06339038118551643), np.float64(-0.08242029595027049), np.float64(-0.06287747396703129), np.float64(-0.10814392031150151), np.float64(-0.0948707364467846), np.float64(-0.0826411298535465), np.float64(-0.009671378097598937), np.float64(-0.024415186150573486), np.float64(0.011135298550603547), np.float64(-0.08981045445662572), np.float64(-0.0123171651591938), np.float64(-0.03377302482786842), np.float64(-0.05450499926370249), np.float64(-0.05582563937744182), np.float64(-0.0032200451048505834), np.float64(-0.017721163745443344), np.float64(-0.03923386381271729), np.float64(-0.06702063422742383), np.float64(0.010713564544117841), np.float64(-0.022580357283902442), np.float64(-0.004290500428379275), np.float64(-0.061337248303377015), np.float64(-0.14756223032455362), np.float64(-0.07845991505943156), np.float64(0.062041682603696746), np.float64(-0.027323257748899578), np.float64(-0.06322411238030338), np.float64(-0.08380997959564201), np.float64(-0.10980626980167368), np.float64(-0.07250713817440922), np.float64(0.04732886181079187), np.float64(-0.09587799164913477), np.float64(-0.007844497014934155), np.float64(-0.04670293313972423), np.float64(0.004185999276518121), np.float64(-0.0724721543797351), np.float64(0.007139720526881188), np.float64(-0.07976347411618204), np.float64(-0.020266287844608766), np.float64(0.005201437930056369), np.float64(-0.04029484972945179), np.float64(-0.11887849617506095), np.float64(-0.06020868417866182), np.float64(-0.05629432551631284), np.float64(-0.020779981110898717), np.float64(0.046150790561033744), np.float64(-0.01224682109776882), np.float64(-0.06982363902231106), np.float64(-0.09130779372725122), np.float64(-0.043679205957262233), np.float64(-0.0784262992048399), np.float64(-0.021213933585984), np.float64(-0.014546552551957264), np.float64(0.010164522391669279), np.float64(-0.03929073725020686), np.float64(-0.03521693209938525), np.float64(-0.07306453585471898), np.float64(0.04940175179999538), np.float64(-0.14998033892541093), np.float64(-0.05449504472036322), np.float64(-0.05994557960475229), np.float64(-0.09874570831896756), np.float64(0.02753573437681882), np.float64(0.014442107796838966), np.float64(-0.03850251439793405), np.float64(-0.01200067993122427), np.float64(0.030497218900658), np.float64(-0.013414523437247895), np.float64(-0.0963238236934639), np.float64(0.004486858887233135), np.float64(-0.12524173798892402), np.float64(-0.014513235797941351), np.float64(-0.019938995152158343), np.float64(-0.07731085946621159), np.float64(-0.06259745809905892), np.float64(-0.0015560586318329604), np.float64(-0.05821767689668397), np.float64(-0.0649368605196574), np.float64(0.045762799308022926), np.float64(-0.031493150661883004), np.float64(-0.09724974226322124), np.float64(0.01816287903816217), np.float64(-0.11004902764587451), np.float64(-0.06516894935334343), np.float64(-0.044649719878160354), np.float64(0.035223470742109415), np.float64(-0.019389933972995474), np.float64(-0.1311662757614468), np.float64(-0.05545131928619162), np.float64(-0.12540498015699506), np.float64(-0.12092465176946643), np.float64(-0.004722145774752151), np.float64(-0.09174855897301654), np.float64(-0.009079633643952608), np.float64(-0.06090402736109961), np.float64(-0.021868073070384717), np.float64(-0.07591437333427978), np.float64(0.008111748257999494), np.float64(0.02688246113473673), np.float64(0.04051622704095946), np.float64(-0.06970098513709962), np.float64(-0.02941729046905483), np.float64(-0.014916036390017089), np.float64(-0.03646718323453486), np.float64(0.0517804695370356), np.float64(-0.11613480052255831), np.float64(-0.05346941798020227), np.float64(-0.043682140990055685), np.float64(0.00035636600338035475), np.float64(-0.0745966390362518), np.float64(-0.1066034916063068), np.float64(-0.05686830768602849), np.float64(-0.022027567790689682), np.float64(-0.05303277565147434), np.float64(-0.004957099975900235), np.float64(-0.02398004049379375), np.float64(-0.06996961328886202), np.float64(-0.07522899076736324), np.float64(-0.02525383330260957), np.float64(-0.04616775031040422), np.float64(-0.045136093788658085), np.float64(-0.061449576924603726), np.float64(-0.17766466318122143), np.float64(-0.054927583218246506), np.float64(-0.030971811701907548), np.float64(-0.08905102594340393), np.float64(-0.10072267687766079), np.float64(-0.04597352044027078), np.float64(-0.05823125343834896), np.float64(-0.10992520853862202), np.float64(-0.04938057823195861), np.float64(-0.027422652081552323), np.float64(-0.03280775516437554), np.float64(-0.004861770230134826), np.float64(-0.04802240662658634), np.float64(-0.056945200936615314), np.float64(-0.06384701755858775), np.float64(-0.13575640802931077), np.float64(-0.0914786669440572), np.float64(0.013521466914767214), np.float64(-0.06611404164991169), np.float64(-0.1897746168878798), np.float64(-0.09448355746567223), np.float64(-0.015270608012226013), np.float64(-0.1554415933653023), np.float64(-0.03920334894223969), np.float64(-0.031768426700801315), np.float64(-0.0318428874647042), np.float64(-0.028860508392027102), np.float64(-0.07963602344236678), np.float64(-0.06332615148026201), np.float64(-0.03659626032610565), np.float64(0.10360407415079434), np.float64(-0.012735509054224332), np.float64(-0.04821971225835991), np.float64(-0.020039985407492317), np.float64(-0.09509945438401261), np.float64(-0.09813745563860914), np.float64(0.00847902582742533), np.float64(-0.029609030218957316), np.float64(-0.055593540852358216), np.float64(-0.020822965229547588), np.float64(-0.03305767196155632), np.float64(-0.11010763788071791), np.float64(1.3411606208087613e-05), np.float64(0.010969379263671588), np.float64(-0.12196878609159638), np.float64(-0.01816173707342655), np.float64(-0.04232648636421723), np.float64(-0.0953931559354229), np.float64(-0.19222577636834565), np.float64(-0.10667375017585959), np.float64(-0.05682612130699701), np.float64(-0.034483872204871396), np.float64(-0.0496386241908731), np.float64(-0.07977515854249595), np.float64(-0.054757157351502946), np.float64(-0.08727579593553557), np.float64(-0.03305664152137441), np.float64(-0.09346822678591166), np.float64(-0.019500169718985643), np.float64(-0.0772510805554405), np.float64(-0.08296241905526192), np.float64(0.006709527621046634), np.float64(-0.016707923608196607), np.float64(-0.03226324044828507), np.float64(-0.07068444541302996), np.float64(-0.07791937752955462), np.float64(-0.032985520088608535), np.float64(-0.03822164831218085), np.float64(-0.007773819519753829), np.float64(0.032125432098092106), np.float64(-0.0817773643745616), np.float64(0.0028397107482230105), np.float64(-0.05976287181081952), np.float64(0.010888422349083042), np.float64(-0.01068940061716873), np.float64(-0.038517799499887394), np.float64(-0.055487079721303685), np.float64(0.028531357248941923), np.float64(-0.11055205867270072), np.float64(-0.005872987424603938), np.float64(0.03329926858321813), np.float64(-0.05644538019345216), np.float64(-0.1081654888451135), np.float64(-0.0026251508438233824), np.float64(-0.046805768620181966), np.float64(-0.04261872745284275), np.float64(-0.0018704078983764897), np.float64(-0.026573487436771473), np.float64(-0.08074203562944239), np.float64(0.004712937508009891), np.float64(-0.0629714936667456), np.float64(-0.006519345548090335), np.float64(-0.08357516294925312), np.float64(-0.0569701565726158), np.float64(0.059753572151412186), np.float64(-0.1062691635775007), np.float64(-0.03942635105866485), np.float64(-0.07073713741541411), np.float64(-0.0813770206019642), np.float64(-0.10125627422194806), np.float64(-0.07307444933786486), np.float64(-0.0845229328080958), np.float64(0.00774235439365229), np.float64(-0.020614649125949847), np.float64(-0.06962569816409585), np.float64(-0.019459633364931582), np.float64(-0.013185105598167777), np.float64(-0.014689229746516557), np.float64(-0.047425605574025684), np.float64(-0.13350484333942703), np.float64(-0.06046292501721216), np.float64(-0.0441768636438871), np.float64(0.031713529812447225), np.float64(-0.12121019012865329), np.float64(0.011700659706314422), np.float64(0.010644091322244604), np.float64(-0.10447673622087565), np.float64(-0.02842203453920172), np.float64(-0.08564788409245665), np.float64(-0.06973374160724437), np.float64(-0.1141762162128481), np.float64(-0.1351058518178057), np.float64(-0.030142510287035906), np.float64(0.021854028483012357), np.float64(-0.056162419606465785), np.float64(0.02330766084025071), np.float64(-0.04422199394151744), np.float64(0.02393748866012628), np.float64(-0.056368165853322647), np.float64(-0.029498024940143867), np.float64(-0.02502081145406512), np.float64(-0.07499608537512643), np.float64(-0.0737671750786416), np.float64(-0.024230858317958917), np.float64(-0.052078451518074206), np.float64(-0.056157405214966816), np.float64(-0.05416296795447938), np.float64(-0.09145128607106111), np.float64(-0.0666162374915011), np.float64(-0.027135736220274893), np.float64(-0.05582207674111619), np.float64(-0.05912066186934789), np.float64(-0.0964533369133099), np.float64(-0.028740491048453245), np.float64(-0.13097037058490785), np.float64(-0.06528387951068383), np.float64(-0.04048294184104075), np.float64(-0.10336676355510975), np.float64(-0.1011569885386048), np.float64(-0.012571914500971148), np.float64(-0.026306354804037247), np.float64(-0.1082950416358244), np.float64(0.0008296042404396681), np.float64(-0.11291107191866508), np.float64(-0.04764690067665812), np.float64(-0.051324001858901624), np.float64(-0.008290362092514603), np.float64(-0.18343666074585532), np.float64(-0.07186311660034814), np.float64(-0.04693566644937885), np.float64(-0.07455595601205463), np.float64(-0.013113633322292366), np.float64(0.07144095613245151), np.float64(0.002676950185171127), np.float64(-0.042768207757932775), np.float64(-0.06910072134473007), np.float64(-0.0448352320096831), np.float64(-0.0908931958641247), np.float64(-0.005144476438220859), np.float64(-0.05180102883662871), np.float64(-0.07457003805408628), np.float64(-0.07425500955130743), np.float64(-0.09386287335804758), np.float64(-0.10577180595581781), np.float64(-0.09516626258699383), np.float64(-0.07684683973310522), np.float64(-0.032456582462244254), np.float64(-0.03736370338460993), np.float64(0.01180185228588144), np.float64(0.017607156614857216), np.float64(-0.0010888442312893423), np.float64(-0.03655615485343998), np.float64(-0.16866536168117172), np.float64(-0.02205544106018076), np.float64(-0.12224379310415648), np.float64(-0.15495428982070916), np.float64(-0.07945642643762599), np.float64(-0.07212206904077184), np.float64(-0.0733890337852878), np.float64(-0.04568178271814095), np.float64(-0.09466515696012848), np.float64(-0.015112285827103247), np.float64(-0.06741020091467391), np.float64(-0.09240620371930293), np.float64(-0.05129151698533862), np.float64(-0.09335958698641883), np.float64(-0.0437270199411043), np.float64(-0.08071832149806278), np.float64(0.008206477746772942), np.float64(-0.022410714547569325), np.float64(-0.038776715507428214), np.float64(-0.06757286120853845), np.float64(-0.09514165092571573), np.float64(-0.029970412076291343), np.float64(-0.06392441360602226), np.float64(-0.07589043738841031), np.float64(-0.062248437746442134), np.float64(-0.06859532075808915), np.float64(-0.07236398689041404), np.float64(0.0031889936933231127), np.float64(-0.05062739870863091), np.float64(-0.017399640385308855), np.float64(-0.024016142231002985), np.float64(-0.08168349643110404), np.float64(-0.025258982776639818), np.float64(0.006470677718272269), np.float64(0.010572182239893318), np.float64(-0.01860299037583771), np.float64(-0.06096505839437115), np.float64(-0.08364841581399188), np.float64(-0.06246184401783331), np.float64(0.015843658137004137), np.float64(-0.01605707403071941), np.float64(-0.03922757786361558), np.float64(-0.07478770712345637), np.float64(-0.01748507851646568), np.float64(-0.03239719501864659), np.float64(-0.13839161133353745), np.float64(0.03325447677809094), np.float64(-0.013043871522379263), np.float64(-0.0023090736446622403), np.float64(-0.02439984822525093), np.float64(0.07853308542329857), np.float64(0.0023470228361754083), np.float64(-0.029549757552540877), np.float64(0.011700941822724952), np.float64(-0.05834014071669797), np.float64(-0.10403730358633162), np.float64(-0.042435373930993045), np.float64(-0.0710083377265901)]

In [20]:
print(len(expectancy_list))

p95 = np.percentile(expectancy_list, 95)                  # ngưỡng phân vị 95
print(f"p95 = {p95}")
# max_expectancy = max(expectancy_list_2)
print(f"max = {max(expectancy_list)}")
mean_expectancy = np.mean(expectancy_list)
print(f"mean = {mean_expectancy}")
print(f"min = {min(expectancy_list)}")
print(f"gap = {-0.06797 - mean_expectancy}")

df_result = pd.DataFrame({'expectancy' : expectancy_list})
rank = (df_result['expectancy'] <= -0.06797).mean() * 100 
print(f"rank = {rank}")
p_value = ((df_result['expectancy'] >= -0.06797).sum() + 1) / (len(df_result['expectancy']) + 1)
print(f"p_value = {p_value}")

print(len(winrate_list))

p95_winrate = np.percentile(winrate_list, 95)                  # ngưỡng phân vị 95
print(f"p95 = {p95_winrate}")
# max_expectancy = max(expectancy_list_2)
print(f"max = {max(winrate_list)}")
mean_winrate = np.mean(winrate_list)
print(f"mean = {mean_winrate}")
print(f"min = {min(winrate_list)}")
print(f"gap = {33.21799 - mean_winrate}")

500
p95 = 0.02980341136542391
max = 0.10963342416583462
mean = -0.04596080161428236
min = -0.19222577636834565
gap = -0.022009198385717646
rank = 32.4
p_value = 0.6766467065868264
500
p95 = 37.04439096135847
max = 40.74074074074074
mean = 33.305330064260744
min = 26.209677419354836
gap = -0.08734006426074359